### In case you're interested, the code to generate this list looks like this:
#    const cities = require('all-the-cities'); 
#    a = cities.filter(city => city.population >= 100000);
#    var new_arr = [];
#    a.forEach(city =>{
#       new_arr.push(city.name);
#    })
#    console.dir(new_arr,{'maxArrayLength': null})
### Do keep in mind that you first have to install the all-the-cities package via npm like this: npm install all-the-cities --save

thousands_of_cities = [
  'Ras Al Khaimah City',
  'Dubai',
  'Sharjah',
  'Ajman City',
  'Abu Dhabi',
  'Musaffah',
  'Mazār-e Sharīf',
  'Kunduz',
  'Kandahār',
  'Kabul',
  'Jalālābād',
  'Herāt',
  'Ghazni',
  'Gardez',
  'Balkh',
  'Baghlān',
  'Elbasan',
  'Tirana',
  'Durrës',
  'Yerevan',
  'Vanadzor',
  'Gyumri',
  'N’dalatando',
  'Luanda',
  'Lubango',
  'Lobito',
  'Cuito',
  'Huambo',
  'Benguela',
  'Villa Lugano',
  'Tandil',
  'Resistencia',
  'Quilmes',
  'Posadas',
  'Pilar',
  'Morón',
  'Merlo',
  'Mar del Plata',
  'La Plata',
  'Formosa',
  'Corrientes',
  'Concordia',
  'Buenos Aires',
  'Berazategui',
  'Belgrano',
  'Santiago del Estero',
  'Santa Rosa',
  'Santa Fe',
  'San Salvador de Jujuy',
  'San Rafael',
  'San Nicolás de los Arroyos',
  'San Miguel de Tucumán',
  'San Luis',
  'San Juan',
  'San Fernando del Valle de Catamarca',
  'Salta',
  'Rosario',
  'Río Cuarto',
  'Paraná',
  'Neuquén',
  'Mendoza',
  'La Rioja',
  'Córdoba',
  'Comodoro Rivadavia',
  'Bahía Blanca',
  'Balvanera',
  'San Miguel',
  'José C. Paz',
  'Vienna',
  'Simmering',
  'Salzburg',
  'Ottakring',
  'Linz',
  'Innsbruck',
  'Graz',
  'Floridsdorf',
  'Favoriten',
  'Donaustadt',
  'Rockingham',
  'Perth',
  'Darwin',
  'Adelaide',
  'Townsville',
  'Toowoomba',
  'Sydney',
  'Newcastle',
  'Melbourne',
  'Launceston',
  'Hobart',
  'Gold Coast',
  'Geelong',
  'Wollongong',
  'Canberra',
  'Cairns',
  'Brisbane',
  'Bendigo',
  'Logan City',
  'Lankaran',
  'Yevlakh',
  'Sumqayıt',
  'Ganja',
  'Baku',
  'Zenica',
  'Tuzla',
  'Sarajevo',
  'Mostar',
  'Banja Luka',
  'Tungi',
  'Sylhet',
  'Jamālpur',
  'Shibganj',
  'Sātkhira',
  'Sirajganj',
  'Narsingdi',
  'Shāhzādpur',
  'Rājshāhi',
  'Nārāyanganj',
  'Nāgarpur',
  'Mymensingh',
  'Comilla',
  'Rangpur',
  'Kushtia',
  'Dhaka',
  'Bhairab Bāzār',
  'Bagerhat',
  'Sonārgaon',
  'Pār Naogaon',
  'Farīdpur',
  'Dinājpur',
  'Chittagong',
  'Cox’s Bāzār',
  'Khulna',
  'Barisāl',
  'Jessore',
  'Pābna',
  'Tāngāil',
  'Bogra',
  'Nawābganj',
  'Sherpur',
  'Saidpur',
  'Puthia',
  'Natore',
  'Paltan',
  'Namur',
  'Liège',
  'Gent',
  'Charleroi',
  'Brussels',
  'Brugge',
  'Antwerpen',
  'Ouagadougou',
  'Bobo-Dioulasso',
  'Varna',
  'Stara Zagora',
  'Sofia',
  'Ruse',
  'Plovdiv',
  'Pleven',
  'Burgas',
  'Manama',
  'Bujumbura',
  'Porto-Novo',
  'Parakou',
  'Kandi',
  'Djougou',
  'Cotonou',
  'Bohicon',
  'Abomey-Calavi',
  'Tarija',
  'Sucre',
  'Santa Cruz de la Sierra',
  'Sacaba',
  'Potosí',
  'Oruro',
  'La Paz',
  'Cochabamba',
  'Vitória de Santo Antão',
  'Timon',
  'Teresina',
  'Sobral',
  'São Luís',
  'Santa Rita',
  'Santarém',
  'Recife',
  'Petrolina',
  'Paulista',
  'Parnamirim',
  'Parnaíba',
  'Olinda',
  'Natal',
  'Mossoró',
  'Maracanaú',
  'Marabá',
  'Maceió',
  'Macapá',
  'Juazeiro do Norte',
  'João Pessoa',
  'Jaboatão',
  'Imperatriz',
  'Garanhuns',
  'Fortaleza',
  'Caxias',
  'Caucaia',
  'Castanhal',
  'Caruaru',
  'Campina Grande',
  'Cabo',
  'Belém',
  'Arapiraca',
  'Araguaína',
  'Ananindeua',
  'Volta Redonda',
  'Vitória da Conquista',
  'Vitória',
  'Vila Velha',
  'Viamão',
  'Várzea Paulista',
  'Várzea Grande',
  'Varginha',
  'Uruguaiana',
  'Umuarama',
  'Uberlândia',
  'Uberaba',
  'Toledo',
  'Teresópolis',
  'Teófilo Otoni',
  'Taubaté',
  'Taboão da Serra',
  'Suzano',
  'Sumaré',
  'Sorocaba',
  'Sete Lagoas',
  'Serra',
  'Sapucaia',
  'São Vicente',
  'São Paulo',
  'São Leopoldo',
  'São José dos Pinhais',
  'São José dos Campos',
  'São José do Rio Preto',
  'São José',
  'São João de Meriti',
  'São Carlos',
  'São Caetano do Sul',
  'São Bernardo do Campo',
  'Santos',
  'Santo André',
  'Santa Maria',
  'Santa Luzia',
  'Santa Cruz do Sul',
  "Santa Bárbara d'Oeste",
  'Salvador',
  'Rondonópolis',
  'Rio Verde',
  'Rio Grande',
  'Rio de Janeiro',
  'Rio das Ostras',
  'Rio Claro',
  'Ribeirão Preto',
  'Ribeirão Pires',
  'Ribeirão das Neves',
  'Resende',
  'Queimados',
  'Presidente Prudente',
  'Praia Grande',
  'Pouso Alegre',
  'Porto Seguro',
  'Porto Alegre',
  'Ponta Grossa',
  'Poços de Caldas',
  'Poá',
  'Piracicaba',
  'Pindamonhangaba',
  'Petrópolis',
  'Pelotas',
  'Patos de Minas',
  'Passo Fundo',
  'Paranaguá',
  'Palhoça',
  'Osasco',
  'Novo Hamburgo',
  'Nova Iguaçu',
  'Nova Friburgo',
  'Nossa Senhora do Socorro',
  'Niterói',
  'Nilópolis',
  'Montes Claros',
  'Mogi Guaçu',
  'Mogi das Cruzes',
  'Mauá',
  'Maringá',
  'Marília',
  'Macaé',
  'Luziânia',
  'Londrina',
  'Linhares',
  'Limeira',
  'Lages',
  'Jundiaí',
  'Juiz de Fora',
  'Joinville',
  'Jequié',
  'Jaú',
  'Jaraguá do Sul',
  'Jandira',
  'Jacareí',
  'Itu',
  'Itaquaquecetuba',
  'Itapevi',
  'Itapetininga',
  'Itapecerica da Serra',
  'Itajaí',
  'Itaguaí',
  'Itabuna',
  'Itaboraí',
  'Ipatinga',
  'Indaiatuba',
  'Ilhéus',
  'Ibirité',
  'Hortolândia',
  'Guarulhos',
  'Guarujá',
  'Guaratinguetá',
  'Guarapuava',
  'Guarapari',
  'Gravataí',
  'Governador Valadares',
  'Goiânia',
  'Franco da Rocha',
  'Francisco Morato',
  'Franca',
  'Foz do Iguaçu',
  'Florianópolis',
  'Ferraz de Vasconcelos',
  'Feira de Santana',
  'Eunápolis',
  'Esmeraldas',
  'Embu',
  'Duque de Caxias',
  'Dourados',
  'Divinópolis',
  'Diadema',
  'Curitiba',
  'Cuiabá',
  'Cubatão',
  'Criciúma',
  'Cotia',
  'Coronel Fabriciano',
  'Contagem',
  'Conselheiro Lafaiete',
  'Colombo',
  'Colatina',
  'Chapecó',
  'Caxias do Sul',
  'Catanduva',
  'Cascavel',
  'Carapicuíba',
  'Canoas',
  'Campos dos Goytacazes',
  'Campo Grande',
  'Campinas',
  'Camaçari',
  'Cachoeiro de Itapemirim',
  'Cachoeirinha',
  'Cabo Frio',
  'Brasília',
  'Bragança Paulista',
  'Botucatu',
  'Blumenau',
  'Birigui',
  'Betim',
  'Belo Horizonte',
  'Belford Roxo',
  'Bauru',
  'Barueri',
  'Barretos',
  'Barreiras',
  'Barra Mansa',
  'Barbacena',
  'Atibaia',
  'Assis',
  'Araucária',
  'Araruama',
  'Araras',
  'Araraquara',
  'Araçatuba',
  'Aracaju',
  'Apucarana',
  'Angra dos Reis',
  'Anápolis',
  'Americana',
  'Alagoinhas',
  'Guaíba',
  'Palmas',
  'Rio Branco',
  'Porto Velho',
  'Manaus',
  'Boa Vista',
  'Ji Paraná',
  'Aparecida de Goiânia',
  'Jaboatão dos Guararapes',
  'Lauro de Freitas',
  'Parauapebas',
  'Pinhais',
  'Simões Filho',
  'Sinop',
  'Planaltina',
  'Nassau',
  'Gaborone',
  'Vitebsk',
  'Salihorsk',
  'Pinsk',
  'Orsha',
  'Navapolatsk',
  'Minsk',
  'Mazyr',
  'Maladzyechna',
  'Mahilyow',
  'Hrodna',
  "Homyel'",
  'Brest',
  'Barysaw',
  'Baranovichi',
  'Babruysk',
  'Abbotsford',
  'Barrie',
  'Brampton',
  'Burlington',
  'Burnaby',
  'Calgary',
  'Cambridge',
  'Coquitlam',
  'Dartmouth',
  'Delta',
  'Edmonton',
  'Etobicoke',
  'Gatineau',
  'Greater Sudbury',
  'Guelph',
  'Hamilton',
  'Kelowna',
  'Kingston',
  'Kitchener',
  'Laval',
  'London',
  'Longueuil',
  'Markham',
  'Milton',
  'Mississauga',
  'Moncton',
  'Montréal',
  'Nepean',
  'North York',
  'Oakville',
  'Oshawa',
  'Ottawa',
  'Regina',
  'Richmond',
  'Richmond Hill',
  'Saguenay',
  'Saskatoon',
  'Sherbrooke',
  'St. Catharines',
  'Surrey',
  'Toronto',
  'Trois-Rivières',
  'Vancouver',
  'Vaughan',
  'Victoria',
  'Windsor',
  'Winnipeg',
  'Halifax',
  'Québec',
  'Lévis',
  'Sydney',
  'Scarborough',
  'Okanagan',
  'Ladner',
  'East York',
  'Uvira',
  'Tshikapa',
  'Mwene-Ditu',
  'Mbuji-Mayi',
  'Kisangani',
  'Kindu',
  'Kananga',
  'Kalemie',
  'Isiro',
  'Ilebo',
  'Goma',
  'Gandajika',
  'Butembo',
  'Bukavu',
  'Beni',
  'Lubumbashi',
  'Likasi',
  'Kolwezi',
  'Mbandaka',
  'Matadi',
  'Kinshasa',
  'Kikwit',
  'Gemena',
  'Boma',
  'Bandundu',
  'Masina',
  'Bimbo',
  'Bangui',
  'Pointe-Noire',
  'Dolisie',
  'Brazzaville',
  'Zürich',
  'Lausanne',
  'Genève',
  'Bern',
  'Basel',
  'Yamoussoukro',
  'San-Pédro',
  'Man',
  'Korhogo',
  'Gagnoa',
  'Divo',
  'Daloa',
  'Bouaké',
  'Anyama',
  'Abobo',
  'Abidjan',
  'Abengourou',
  'Viña del Mar',
  'Valparaíso',
  'Valdivia',
  'Temuco',
  'Talcahuano',
  'Talca',
  'Santiago',
  'San Bernardo',
  'Rancagua',
  'Quilpué',
  'Punta Arenas',
  'Puerto Montt',
  'Puente Alto',
  'Osorno',
  'Los Ángeles',
  'La Serena',
  'Iquique',
  'Curicó',
  'Coquimbo',
  'Copiapó',
  'Concepción',
  'Chillán',
  'Calama',
  'Arica',
  'Antofagasta',
  'La Pintana',
  'Lo Prado',
  'Yaoundé',
  'Nkongsamba',
  'Ngaoundéré',
  'Mokolo',
  'Mbouda',
  'Maroua',
  'Loum',
  'Kumba',
  'Kousséri',
  'Garoua',
  'Edéa',
  'Douala',
  'Bertoua',
  'Bamenda',
  'Bafoussam',
  'Lhasa',
  'Kashgar',
  'Jiayuguan',
  'Hotan',
  'Xinyuan',
  'Ürümqi',
  'Turpan',
  'Shihezi',
  'Qapqal',
  'Korla',
  'Karamay',
  'Hami',
  'Changji',
  'Aral',
  'Altay',
  'Aksu',
  'Zunyi',
  'Zoucheng',
  'Zigong',
  'Zhuzhou',
  'Zhumadian',
  'Shangqiu',
  'Zhuji',
  'Mizhou',
  'Zhoukou',
  'Zhoucun',
  'Yuxi',
  'Zhicheng',
  'Zhenzhou',
  'Zhenjiang',
  'Zhengzhou',
  'Xinghua',
  'Zhaotong',
  'Zhaoqing',
  'Zhaoyuan',
  'Zhanjiang',
  'Zhangzhou',
  'Zhangye',
  'Zibo',
  'Anyang',
  'Zhabei',
  'Zaozhuang',
  'Zaoyang',
  'Yuyao',
  'Kunshan',
  'Yunfu',
  'Yuncheng',
  'Yulin',
  'Yuci',
  'Qianjiang',
  'Zhongxiang',
  'Chengzhong',
  'Yinchuan',
  'Qingzhou',
  'Yichun',
  'Yichang',
  'Yibin',
  'Yantai',
  'Yangzhou',
  'Yangshuo',
  'Yangquan',
  'Yancheng',
  'Tongshan',
  'Shangrao',
  'Xuchang',
  'Xuanzhou',
  'Xiuying',
  'Xiulin',
  'Xinzhou',
  'Xinyang',
  'Xinxiang',
  'Xintai',
  'Xinpu',
  'Xinji',
  'Xining',
  'Xingtai',
  'Ankang',
  'Xindi',
  'Sanshui',
  'Xichang',
  'Xiazhen',
  'Xiaogan',
  'Xianyang',
  'Xiantao',
  'Xianning',
  'Zhuhai',
  'Xiangtan',
  'Xiangyang',
  'Xi’an',
  'Xiamen',
  'Wuzhou',
  'Wuxue',
  'Wuxi',
  'Dongyang',
  'Changde',
  'Wuhu',
  'Wuhan',
  'Wuhai',
  'Wuda',
  'Wenzhou',
  'Tianfu',
  'Wenchang',
  'Weinan',
  'Weihai',
  'Weifang',
  'Wanxian',
  'Wafangdian',
  'Tongzhou',
  'Wusong',
  'Tianshui',
  'Tianjin',
  'Chengtangcun',
  'Tangshan',
  'Tanggu',
  'Taizhou',
  'Taiyuan',
  'Taishan',
  'Tai’an',
  'Suzhou',
  'Suizhou',
  'Suining',
  'Songjiang',
  'Shizuishan',
  'Shiyan',
  'Shiqiao',
  'Shiqi',
  'Shilong',
  'Tongchuanshi',
  'Shijiazhuang',
  'Shenzhen',
  'Shashi',
  'Shaping',
  'Shaoxing',
  'Shaowu',
  'Shaoguan',
  'Shanwei',
  'Shantou',
  'Shanghai',
  'Shahecheng',
  'Sanya',
  'Sanming',
  'Jieyang',
  'Rizhao',
  'Qujing',
  'Quanzhou',
  'Qinzhou',
  'Qinhuangdao',
  "Huai'an",
  'Qingdao',
  'Qingyuan',
  'Puyang Chengguanzhen',
  'Puyang',
  'Putian',
  'Puqi',
  'Pulandian',
  'Pingxiang',
  'Pingshan',
  'Pingliang',
  'Pingdingshan',
  'Dadukou',
  'Ningbo',
  'Neijiang',
  'Nanyang',
  'Nantong',
  'Nanping',
  'Nanning',
  'Nanjing',
  'Nanchong',
  'Nanchang',
  'Mingshui',
  'Mianyang',
  'Mentougou',
  'Meizhou',
  'Wuchuan',
  'Majie',
  'Macheng',
  'Maba',
  'Luqiao',
  'Luoyang',
  'Luoyang',
  'Luohe',
  'Kangding',
  'Luancheng',
  'Loudi',
  'Guankou',
  'Puning',
  'Linyi',
  'Linxia Chengguanzhen',
  'Linxi',
  'Linshui',
  'Qingnian',
  'Linhai',
  'Linfen',
  'Licheng',
  'Liaocheng',
  'Lianran',
  'Wuwei',
  'Lianjiang',
  'Leshan',
  'Lengshuijiang',
  'Leiyang',
  'Lecheng',
  'Laohekou',
  'Lanzhou',
  'Langfang',
  'Laizhou',
  'Laiyang',
  'Laiwu',
  'Kunming',
  'Kaiyuan',
  'Kaifeng',
  'Jiujiang',
  'Qianzhou',
  'Jinzhou',
  'Jining',
  'Jinhua',
  'Jingzhou',
  'Jingmen',
  'Jingling',
  'Jingdezhen',
  'Jinchang',
  'Jincheng',
  'Jinan',
  'Jieshou',
  'Jieshi',
  'Jiazi',
  'Jiaxing',
  'Jiaozuo',
  'Jiaozhou',
  'Jiangmen',
  'Yangjiang',
  'Ji’an',
  'Guangyuan',
  'Qionghai',
  'Huzhou',
  'Humen',
  'Huizhou',
  'Huicheng',
  'Xinhui',
  'Huayin',
  'Huangzhou',
  'Huangyan',
  'Huangshi',
  'Dasha',
  'Huanggang',
  'Daxing',
  'Huainan',
  'Huaihua',
  'Huaibei',
  'Heze',
  'Yiyang',
  'Hepo',
  'Hengyang',
  'Hengshui',
  'Hefei',
  'Hebi',
  'Hanzhong',
  'Hangzhou',
  'Hangu',
  'Handan',
  'Jiaojiang',
  'Haimen',
  'Haikou',
  'Haikou',
  'Guli',
  'Guiyang',
  'Guilin',
  'Guangzhou',
  'Guangshui',
  'Gejiu',
  'Gaozhou',
  'Gaoping',
  'Gaomi',
  'Fuzhou',
  'Fuyang',
  'Fuling',
  'Foshan',
  'Ezhou',
  'Encheng',
  'Shengli',
  'Dongtai',
  'Donghai',
  'Dongguan',
  'Dingzhou',
  'Dezhou',
  'Deyang',
  'Lijiang',
  'Dazhou',
  'Dawukou',
  'Danshui',
  'Daliang',
  'Dalian',
  'Dali',
  'Chuzhou',
  'Yangchun',
  'Chongqing',
  'Chizhou',
  'Chenzhou',
  'Jiangyin',
  'Chengdu',
  'Chenghua',
  'Chaozhou',
  'Chaohu',
  'Changzhou',
  'Changzhi',
  'Changsha',
  'Cangzhou',
  'Buhe',
  'Bozhou',
  'Boshan',
  'Binzhou',
  'Bengbu',
  'Beijing',
  'Beihai',
  'Beibei',
  'Baoding',
  'Baiyin',
  'Shangyu',
  'Anshun',
  'Anqiu',
  'Anqing',
  'Anbu',
  'Jiangyou',
  'Suzhou',
  'Zhongshan',
  'Dadonghai',
  'Lianghu',
  'Yueyang',
  'Zhaodong',
  'Zhangjiakou',
  'Zhalantun',
  'Yushu',
  'Yingkou',
  'Yichun',
  'Yanji',
  'Yakeshi',
  'Zhangjiakou Shi Xuanhua Qu',
  'Xilin Hot',
  'Ulanhot',
  'Tongliao',
  'Tonghua',
  'Tieling',
  'Tieli',
  'Guangming',
  'Sujiatun',
  'Suihua',
  'Siping',
  'Shunyi',
  'Shuangyashan',
  'Shuangcheng',
  'Shenyang',
  'Shanhaiguan',
  'Fendou',
  'Taihecun',
  'Qiqihar',
  'Songyuan',
  'Panshan',
  'Nehe',
  'Nanpiao',
  'Lianhe',
  'Mudanjiang',
  'Longjing',
  'Longjiang',
  'Longfeng',
  'Liaoyuan',
  'Liaoyang',
  'Kaiyuan',
  'Jixi',
  'Jiutai',
  'Jiupu',
  'Jishu',
  'Jinzhou',
  'Lianshan',
  'Jining',
  'Jilin',
  'Minzhu',
  'Jiamusi',
  'Jalai Nur',
  'Jiagedaqi',
  'Hulan Ergi',
  'Hulan',
  'Huadian',
  'Honggang',
  'Hohhot',
  'Fendou',
  'Heihe',
  'Hegang',
  'Harbin',
  'Hailun',
  'Hailar',
  'Haicheng',
  'Gongzhuling',
  'Fuyu',
  'Fuxin',
  'Fushun',
  'Fengcheng',
  'Dunhua',
  'Dongling',
  'Dongxing',
  'Dehui',
  'Datong',
  'Daqing',
  'Dandong',
  'Chifeng',
  'Chengde',
  'Chaoyang',
  'Changchun',
  'Benxi',
  'Beipiao',
  'Bei’an',
  'Baotou',
  'Baoshan',
  'Baicheng',
  'Baishan',
  'Anshan',
  'Anda',
  'Acheng',
  'Changshu City',
  'Jiashan',
  'Fenghuang',
  'Zhu Cheng City',
  'Shangri-La',
  'Ordos',
  'Wenshan City',
  'Liupanshui',
  'Jianshui',
  'Huocheng',
  'Bayan Nur',
  'Villavicencio',
  'Valledupar',
  'Tunja',
  'Tuluá',
  'Soledad',
  'Sogamoso',
  'Soacha',
  'Sincelejo',
  'Santa Marta',
  'Popayán',
  'Pereira',
  'Pasto',
  'Palmira',
  'Neiva',
  'Montería',
  'Medellín',
  'Manizales',
  'Malambo',
  'Maicao',
  'Magangué',
  'Itagüí',
  'Ibagué',
  'Girón',
  'Girardot City',
  'Floridablanca',
  'Florencia',
  'Envigado',
  'Dosquebradas',
  'Cúcuta',
  'Cartago',
  'Cartagena',
  'Cali',
  'Guadalajara de Buga',
  'Buenaventura',
  'Bucaramanga',
  'Bogotá',
  'Bello',
  'Barranquilla',
  'Barrancabermeja',
  'Armenia',
  'San José',
  'Santiago de Cuba',
  'Santa Clara',
  'San Miguel del Padrón',
  'Sancti Spíritus',
  'Pinar del Río',
  'Palma Soriano',
  'Matanzas',
  'Manzanillo',
  'Las Tunas',
  'Havana',
  'Holguín',
  'Guantánamo',
  'Guanabacoa',
  'Cienfuegos',
  'Ciego de Ávila',
  'Cerro',
  'Camagüey',
  'Bayamo',
  'Arroyo Naranjo',
  'Alamar',
  'Ciudad Camilo Cienfuegos',
  'Centro Habana',
  'Boyeros',
  'Diez de Octubre',
  'Praia',
  'Willemstad',
  'Nicosia',
  'Limassol',
  'Prague',
  'Pilsen',
  'Ostrava',
  'Olomouc',
  'Brno',
  'Würzburg',
  'Wuppertal',
  'Wolfsburg',
  'Witten',
  'Wiesbaden',
  'Ulm',
  'Trier',
  'Stuttgart',
  'Solingen',
  'Siegen',
  'Schöneberg',
  'Salzgitter',
  'Saarbrücken',
  'Rostock',
  'Reutlingen',
  'Remscheid',
  'Regensburg',
  'Recklinghausen',
  'Prenzlauer Berg',
  'Potsdam',
  'Pforzheim',
  'Paderborn',
  'Osnabrück',
  'Oldenburg',
  'Offenbach',
  'Oberhausen',
  'Nürnberg',
  'Nippes',
  'Neue Neustadt',
  'Neuss',
  'Neukölln',
  'Münster',
  'Munich',
  'Mülheim',
  'Mönchengladbach',
  'Moers',
  'Marzahn',
  'Mannheim',
  'Mainz',
  'Magdeburg',
  'Ludwigshafen am Rhein',
  'Lübeck',
  'Leverkusen',
  'Leipzig',
  'Kreuzberg',
  'Krefeld',
  'Köln',
  'Koblenz',
  'Kiel',
  'Kassel',
  'Karlsruhe',
  'Jena',
  'Ingolstadt',
  'Hildesheim',
  'Herne',
  'Heilbronn',
  'Heidelberg',
  'Harburg',
  'Hannover',
  'Hamm',
  'Wandsbek',
  'Marienthal',
  'Hamburg-Mitte',
  'Eimsbüttel',
  'Altona',
  'Hamburg',
  'Halle (Saale)',
  'Hagen',
  'Göttingen',
  'Gera',
  'Gelsenkirchen',
  'Fürth',
  'Friedrichshain',
  'Freiburg',
  'Frankfurt am Main',
  'Essen',
  'Erlangen',
  'Erfurt',
  'Düsseldorf',
  'Duisburg',
  'Dresden',
  'Dortmund',
  'Darmstadt',
  'Chemnitz',
  'Charlottenburg',
  'Bremerhaven',
  'Bremen',
  'Braunschweig',
  'Bottrop',
  'Bonn',
  'Bochum',
  'Bielefeld',
  'Berlin',
  'Bergisch Gladbach',
  'Augsburg',
  'Aachen',
  'Bochum-Hordel',
  'Bergedorf',
  'Hamburg-Nord',
  'Djibouti',
  'Odense',
  'Copenhagen',
  'Århus',
  'Aalborg',
  'Santo Domingo',
  'Santiago de los Caballeros',
  'San Pedro de Macorís',
  'San Francisco de Macorís',
  'Puerto Plata',
  'Salvaleón de Higüey',
  'Punta Cana',
  'La Romana',
  'Concepción de La Vega',
  'San Cristóbal',
  'Bella Vista',
  'Santo Domingo Oeste',
  'Santo Domingo Este',
  'Boumerdas',
  'Tlemcen',
  'Tizi Ouzou',
  'Tiaret',
  'Tébessa',
  'Souk Ahras',
  'Skikda',
  'Sidi Bel Abbès',
  'Sétif',
  'Saïda',
  'Relizane',
  'Oum el Bouaghi',
  'Ouargla',
  'Oran',
  'M’Sila',
  'Mostaganem',
  'Médéa',
  'Mascara',
  'Laghouat',
  'Khenchela',
  'Jijel',
  'Guelma',
  'El Oued',
  'El Eulma',
  'Chlef',
  'El Achir',
  'Ech Chettia',
  'Djelfa',
  'Constantine',
  'Bordj el Kiffan',
  'Bordj Bou Arreridj',
  'Blida',
  'Biskra',
  'Bejaïa',
  'Béchar',
  'Batna',
  'Baraki',
  'Bab Ezzouar',
  'Annaba',
  'Algiers',
  'Aïn Oussera',
  'Aïn Beïda',
  'Santo Domingo de los Colorados',
  'Riobamba',
  'Quito',
  'Quevedo',
  'Portoviejo',
  'Milagro',
  'Manta',
  'Machala',
  'Loja',
  'Ibarra',
  'Guayaquil',
  'Esmeraldas',
  'Eloy Alfaro',
  'Cuenca',
  'Ambato',
  'Tutamandahostel',
  'Tartu',
  'Tallinn',
  'Tanda',
  'Ţalkhā',
  'Sohag',
  'Shibīn al Kawm',
  'Qinā',
  'Qalyūb',
  'Mallawī',
  'Kafr ash Shaykh',
  'Kafr ad Dawwār',
  'Jirjā',
  'Idkū',
  'Idfū',
  'Ḩalwān',
  'Disūq',
  'Dikirnis',
  'Damanhūr',
  'Port Said',
  'Bilqās',
  'Bilbays',
  'Banī Suwayf',
  'Banhā',
  'Zagazig',
  'Asyūţ',
  'Aswan',
  'Suez',
  'Luxor',
  'Cairo',
  'Al Minyā',
  'Al Manşūrah',
  'Al Maḩallah al Kubrá',
  'Giza',
  'Ismailia',
  'Alexandria',
  'Al Ḩawāmidīyah',
  'Al Fayyūm',
  'Arish',
  'Abū Kabīr',
  'New Cairo',
  'Laayoune',
  'Asmara',
  'Valencia',
  'Torrevieja',
  'Telde',
  'Sevilla',
  'Santa Cruz de Tenerife',
  'La Laguna',
  'Palma',
  'Murcia',
  'Marbella',
  'Málaga',
  'Las Palmas de Gran Canaria',
  'Jerez de la Frontera',
  'Jaén',
  'Huelva',
  'Granada',
  'Elche',
  'Dos Hermanas',
  'Córdoba',
  'Castelló de la Plana',
  'Cartagena',
  'Cadiz',
  'Badajoz',
  'Almería',
  'Alicante',
  'Algeciras',
  'Albacete',
  'Zaragoza',
  'Gasteiz / Vitoria',
  'Villaverde',
  'Vigo',
  'Valladolid',
  'Torrejón de Ardoz',
  'Tetuán de las Victorias',
  'Terrassa',
  'Tarragona',
  'Santander',
  'Santa Coloma de Gramenet',
  'Donostia / San Sebastián',
  'Sant Andreu',
  'Salamanca',
  'Sabadell',
  'Reus',
  'Puente de Vallecas',
  'Parla',
  'Pamplona',
  'Oviedo',
  'Ourense',
  'Móstoles',
  'Moratalaz',
  'Mataró',
  'Madrid',
  'Logroño',
  'Lleida',
  'León',
  'Leganés',
  'A Coruña',
  "L'Hospitalet de Llobregat",
  'Hortaleza',
  'Gràcia',
  'Gijón',
  'Getafe',
  'Fuenlabrada',
  'Ciudad Lineal',
  'Chamartín',
  'Burgos',
  'Bilbao',
  'Barcelona',
  'Badalona',
  'Alcorcón',
  'Alcobendas',
  'Alcalá de Henares',
  'Nou Barris',
  'Moncloa-Aravaca',
  'Eixample',
  'Sarrià-Sant Gervasi',
  'Horta-Guinardó',
  'Sants-Montjuïc',
  'Sant Martí',
  'Ciutat Vella',
  'Arganzuela',
  'San Blas-Canillejas',
  'Latina',
  'Usera',
  'Salamanca',
  'Chamberí',
  'Carabanchel',
  'City Center',
  'Retiro',
  'Delicias',
  'Fuencarral-El Pardo',
  'Nazrēt',
  "Mek'ele",
  'Jimma',
  'Gondar',
  'Dire Dawa',
  'Desē',
  'Bishoftu',
  'Bahir Dar',
  'Hawassa',
  'Addis Ababa',
  'Vantaa',
  'Turku',
  'Tampere',
  'Oulu',
  'Helsinki',
  'Espoo',
  'Villeurbanne',
  'Tours',
  'Toulouse',
  'Toulon',
  'Strasbourg',
  'Saint-Étienne',
  'Rouen',
  'Rennes',
  'Reims',
  'Perpignan',
  'Paris',
  'Orléans',
  'Nîmes',
  'Nice',
  'Nantes',
  'Nancy',
  'Mulhouse',
  'Montpellier',
  'Metz',
  'Marseille',
  'Lyon',
  'Limoges',
  'Lille',
  'Le Mans',
  'Le Havre',
  'Grenoble',
  'Dijon',
  'Clermont-Ferrand',
  'Caen',
  'Brest',
  'Boulogne-Billancourt',
  'Bordeaux',
  'Besançon',
  'Argenteuil',
  'Angers',
  'Amiens',
  'Aix-en-Provence',
  'Saint-Quentin-en-Yvelines',
  'Cergy-Pontoise',
  'Port-Gentil',
  'Libreville',
  'York',
  'Worcester',
  'Wolverhampton',
  'Woking',
  'Wigan',
  'City of Westminster',
  'West Bromwich',
  'Watford',
  'Warrington',
  'Walsall',
  'Swindon',
  'Swansea',
  'Sutton Coldfield',
  'Sutton',
  'Sunderland',
  'Stoke-on-Trent',
  'Stockport',
  'Southend-on-Sea',
  'Southampton',
  'Slough',
  'Sheffield',
  'Saint Peters',
  'St Helens',
  'Rotherham',
  'Reading',
  'Preston',
  'Portsmouth',
  'Poole',
  'Plymouth',
  'Peterborough',
  'Oxford',
  'Oldham',
  'Nottingham',
  'Norwich',
  'Northampton',
  'Newport',
  'Newcastle upon Tyne',
  'Milton Keynes',
  'Middlesbrough',
  'Mansfield',
  'Manchester',
  'Maidstone',
  'Luton',
  'London',
  'Liverpool',
  'Lincoln',
  'Leicester',
  'Leeds',
  'Kingston upon Hull',
  'Islington',
  'Ipswich',
  'Huddersfield',
  'High Wycombe',
  'Hastings',
  'Grimsby',
  'Gloucester',
  'Glasgow',
  'Gillingham',
  'Exeter',
  'Enfield Town',
  'Edinburgh',
  'Eastbourne',
  'Dundee',
  'Dudley',
  'Doncaster',
  'Derby',
  'Dagenham',
  'Croydon',
  'Crawley',
  'Coventry',
  'Colchester',
  'Chesterfield',
  'Cheltenham',
  'Chelmsford',
  'Cardiff',
  'Cambridge',
  'Burton upon Trent',
  'Burnley',
  'Bristol',
  'Brighton',
  'Brent',
  'Bradford',
  'Bournemouth',
  'Bolton',
  'Blackpool',
  'Blackburn',
  'Birmingham',
  'Birkenhead',
  'Bexley',
  'Belfast',
  'Bedford',
  'Basingstoke',
  'Basildon',
  'Aberdeen',
  'Telford',
  'Becontree',
  'Mendip',
  'Archway',
  'Tbilisi',
  'Kutaisi',
  'Batumi',
  'Teshi Old Town',
  'Tema',
  'Tamale',
  'Takoradi',
  'Sekondi-Takoradi',
  'Obuase',
  'Medina Estates',
  'Kumasi',
  'Cape Coast',
  'Atsiaman',
  'Accra',
  'Serekunda',
  'Nzérékoré',
  'Kindia',
  'Kankan',
  'Conakry',
  'Camayenne',
  'Malabo',
  'Bata',
  'Piraeus',
  'Peristéri',
  'Pátra',
  'Lárisa',
  'Kallithéa',
  'Irákleion',
  'Athens',
  'Thessaloníki',
  'Villa Nueva',
  'Villa Canales',
  'San Juan Sacatepéquez',
  'Quetzaltenango',
  'Petapa',
  'Mixco',
  'Escuintla',
  'Guatemala City',
  'Bissau',
  'Georgetown',
  'Tsuen Wan',
  'Yuen Long Kau Hui',
  'Kowloon',
  'Hong Kong',
  'Tegucigalpa',
  'San Pedro Sula',
  'La Ceiba',
  'El Progreso',
  'Choloma',
  'Zagreb',
  'Split',
  'Rijeka',
  'Port-de-Paix',
  'Port-au-Prince',
  'Tigwav',
  'Pétionville',
  'Léogâne',
  'Jacmel',
  'Delmas 73',
  'Croix-des-Bouquets',
  'Les Cayes',
  'Carrefour',
  'Okap',
  'Szeged',
  'Nyíregyháza',
  'Miskolc',
  'Debrecen',
  'Zugló',
  'Székesfehérvár',
  'Pécs',
  'Kecskemét',
  'Győr',
  'Budapest',
  'Budapest XI. kerület',
  'Budapest XIII. kerület',
  'Budapest III. kerület',
  'Tebingtinggi',
  'Tanjungbalai',
  'Sunggal',
  'Rantauprapat',
  'Percut',
  'Perbaungan',
  'Pematangsiantar',
  'Padangsidempuan',
  'Medan',
  'Kisaran',
  'Binjai',
  'Belawan',
  'Banda Aceh',
  'Yogyakarta',
  'Weru',
  'Ungaran',
  'Makassar',
  'Ternate',
  'Tegal',
  'Tasikmalaya',
  'Tanjung Pinang',
  'Bandar Lampung',
  'Tangerang',
  'Surakarta',
  'Surabaya',
  'Sumedang Utara',
  'Sumedang',
  'Sukabumi',
  'Sorong',
  'Soreang',
  'Situbondo',
  'Singkawang',
  'Singaraja',
  'Sidoarjo',
  'Serang',
  'Sepatan',
  'Semarang',
  'Sawangan',
  'Samarinda',
  'Salatiga',
  'Rengasdengklok',
  'Rangkasbitung',
  'Purwokerto',
  'Purwodadi',
  'Purwakarta',
  'Probolinggo',
  'Pontianak',
  'Plumbon',
  'Prabumulih',
  'Pemalang',
  'Pekanbaru',
  'Pekalongan',
  'Payakumbuh',
  'Pati',
  'Pasuruan',
  'Paseh',
  'Pasarkemis',
  'Parung',
  'Parepare',
  'Pangkalpinang',
  'Pamulang',
  'Pamanukan',
  'Palu',
  'Palopo',
  'Palembang',
  'Palangkaraya',
  'Padang',
  'Mojokerto',
  'Metro',
  'Mataram',
  'Martapura',
  'Manado',
  'Malang',
  'Magelang',
  'Madiun',
  'Lumajang',
  'Lubuklinggau',
  'Loa Janan',
  'Lembang',
  'Lawang',
  'Labuan Bajo',
  'Kresek',
  'Klaten',
  'Kendari',
  'Kedungwuni',
  'Kediri',
  'Jombang',
  'Jember',
  'Jambi City',
  'Jakarta',
  'Indramayu',
  'Grogol',
  'Gorontalo',
  'Dumai',
  'Depok',
  'Depok',
  'Denpasar',
  'Curug',
  'Citeureup',
  'Cirebon',
  'Ciputat',
  'Cimahi',
  'Cileunyi',
  'Cileungsir',
  'Cikarang',
  'Cikampek',
  'Cibinong',
  'Ciamis',
  'Ciampea',
  'Bontang',
  'Bogor',
  'Blitar',
  'Bengkulu',
  'Bekasi',
  'Baturaja',
  'Batang',
  'Banyuwangi',
  'Banjarmasin',
  'Banjaran',
  'Bangil',
  'Bandung',
  'Balikpapan',
  'Astanajapura',
  'Arjawinangun',
  'Ambon',
  'Adiwerna',
  'Padalarang',
  'Cikupa',
  'Teluknaga',
  'Kupang',
  'Jayapura',
  'Batam',
  'City of Balikpapan',
  'South Tangerang',
  'Dublin',
  'Cork',
  'Jerusalem',
  'Jaffa',
  'Tel Aviv',
  'Rishon LeẔiyyon',
  'Reẖovot',
  'Ramat Gan',
  'Petaẖ Tiqwa',
  'Netanya',
  'H̱olon',
  'Haifa',
  'Bnei Brak',
  'Beersheba',
  'Bat Yam',
  'Ashkelon',
  'Ashdod',
  'West Jerusalem',
  'Yelahanka',
  'Yavatmāl',
  'Yamunānagar',
  'Wardha',
  'Warangal',
  'Vizianagaram',
  'Visakhapatnam',
  'Virār',
  'Vijayawada',
  'Vidisha',
  'Verāval',
  'Vellore',
  'Vejalpur',
  'Vasco da Gama',
  'Varanasi',
  'Vadodara',
  'Uppal Kalan',
  'Unnāo',
  'Ulhasnagar',
  'Ujjain',
  'Udupi',
  'Udgīr',
  'Udaipur',
  'Tumkūr',
  'Thiruvananthapuram',
  'Thrissur',
  'Tonk',
  'Titāgarh',
  'Tiruvottiyūr',
  'Tiruvannāmalai',
  'Tiruppur',
  'Tirupati',
  'Tirunelveli',
  'Tiruchirappalli',
  'Tanjore',
  'Thānesar',
  'Thāne',
  'Teni',
  'Tambaram',
  'Tādepallegūdem',
  'Suriāpet',
  'Surendranagar',
  'Sūrat',
  'Sultānpur',
  'Sūjāngarh',
  'Srinagar',
  'Srikakulam',
  'Sonīpat',
  'Siwān',
  'Sītāpur',
  'Sirsa',
  'Shimla',
  'Silchar',
  'Sīkar',
  'Shyamnagar',
  'Shrīrāmpur',
  'Solāpur',
  'Shivpuri',
  'Shimoga',
  'Shillong',
  'Siliguri',
  'Shāntipur',
  'Shāhjānpur',
  'Seoni',
  'Secunderabad',
  'Sawāi Mādhopur',
  'Satna',
  'Satara',
  'Sāngli',
  'Sambhal',
  'Sambalpur',
  'Salem',
  'Saharsa',
  'Sahāranpur',
  'Saugor',
  'Roorkee',
  'Rohtak',
  'Robertsonpet',
  'Rishra',
  'Rewāri',
  'Rewa',
  'Raurkela',
  'Ratlām',
  'Rānīganj',
  'Ranchi',
  'Rāmpur',
  'Rāmgundam',
  'Rāj-Nāndgaon',
  'Rājkot',
  'Rajapalaiyam',
  'Rājahmundry',
  'Raipur',
  'Raigarh',
  'Rāiganj',
  'Rāichūr',
  'Raebareli',
  'Kollam',
  'Puruliya',
  'Purnia',
  'Puri',
  'Pune',
  'Punāsa',
  'Pudukkottai',
  'Proddatūr',
  'Port Blair',
  'Porbandar',
  'Ponnāni',
  'Puducherry',
  'Pimpri',
  'Pīlibhīt',
  'Phagwāra',
  'Patna',
  'Patiāla',
  'Pathānkot',
  'Pātan',
  'Parbhani',
  'Panvel',
  'Pānīpat',
  'Pānihāti',
  'Palwal',
  'Pallāvaram',
  'Pāli',
  'Pālghāt',
  'Pālanpur',
  'Orai',
  'Ongole',
  'Nowrangapur',
  'Nizāmābād',
  'New Delhi',
  'Nellore',
  'Navsāri',
  'Navadwīp',
  'Nashik',
  'Narela',
  'Nāngloi Jāt',
  'Nandyāl',
  'Nandurbar',
  'Nanded',
  'Nalgonda',
  'Najafgarh',
  'Naihāti',
  'Nagpur',
  'Nāgercoil',
  'Nagda',
  'Nadiād',
  'Mysore',
  'Muzaffarpur',
  'Muzaffarnagar',
  'Murwāra',
  'Monghyr',
  'Mothīhāri',
  'Morena',
  'Morbi',
  'Morādābād',
  'Moga',
  'Mirzāpur',
  'Miriālgūda',
  'Meerut',
  'Medinīpur',
  'Mau',
  'Mathura',
  'Mormugao',
  'Mangalore',
  'Mandya',
  'Mandsaur',
  'Māler Kotla',
  'Mālegaon',
  'Mahbūbnagar',
  'Madurai',
  'Chennai',
  'Madhyamgram',
  'Madanapalle',
  'Machilīpatnam',
  'Ludhiāna',
  'Lucknow',
  'Loni',
  'Latur',
  'Lalitpur',
  'Lakhīmpur',
  'Kurnool',
  'Kumbakonam',
  'Kulti',
  'Kūkatpalli',
  'Krishnanagar',
  'Kozhikode',
  'Kota',
  'Korba',
  'Kolhāpur',
  'Kolār',
  'Kishangarh',
  'Khurja',
  'Khardah',
  'Kharagpur',
  'Khanna',
  'Khandwa',
  'Khammam',
  'Katihar',
  'Kashipur',
  'Karol Bāgh',
  'Karnāl',
  'Karīmnagar',
  'Kanpur',
  'Kanchipuram',
  'Kāmārhāti',
  'Kalyān',
  'Kākināda',
  'Kaithal',
  'Kānchrāpāra',
  'Jūnāgadh',
  'Jalandhar',
  'Jodhpur',
  'Jīnd',
  'Jhunjhunūn',
  'Jhānsi',
  'Jetpur',
  'Jaunpur',
  'Jāmuria',
  'Jamshedpur',
  'Jamnagar',
  'Jammu',
  'Jamālpur',
  'Jalpāiguri',
  'Jālna',
  'Jalgaon',
  'Jaipur',
  'Jagādhri',
  'Jabalpur',
  'Itārsi',
  'Ingrāj Bāzār',
  'Indore',
  'Imphal',
  'Ichalkaranji',
  'Hyderabad',
  'Hugli',
  'Hubli',
  'Hosūr',
  'Hospet',
  'Hoshiārpur',
  'Hoshangābād',
  'Hisar',
  'Hindupur',
  'Hazāribāgh',
  'Hāthras',
  'Hassan',
  'Haridwar',
  'Hardoī',
  'Hāpur',
  'Hāora',
  'Hanumāngarh',
  'Hālīsahar',
  'Haldwani',
  'Hājīpur',
  'Hābra',
  'Gwalior',
  'Gurgaon',
  'Guntur',
  'Guntakal Junction',
  'Guna',
  'Gulbarga',
  'Gudivāda',
  'Gosāba',
  'Gorakhpur',
  'Gorakhpur',
  'Gondiā',
  'Gondal',
  'Gondā City',
  'Godhra',
  'Ghazīpur',
  'Ghāziābād',
  'Gaya',
  'Guwahati',
  'Gangāwati',
  'Gangāpur',
  'Gangānagar',
  'Gandhinagar',
  'Gāndhīdhām',
  'Gadag',
  'Ferozepore',
  'Fīrozābād',
  'Fatehpur',
  'Farrukhābād',
  'Faridabad',
  'Fyzābād',
  'Etāwah',
  'Erode',
  'Ellore',
  'Durgapur',
  'Durg',
  'Dam Dam',
  'Dombivli',
  'Dindigul',
  'Dimāpur',
  'Dibrugarh',
  'Dhūlia',
  'Dhaulpur',
  'Dharmavaram',
  'Dhanbād',
  'Dewas',
  'Deoria',
  'Delhi',
  'Dehri',
  'Dehra Dūn',
  'Davangere',
  'Dārjiling',
  'Darbhanga',
  'Dinapore',
  'Damoh',
  'Cuttack',
  'Cuddapah',
  'Cuddalore',
  'Coimbatore',
  'Cochin',
  'Chūru',
  'Chittaurgarh',
  'Chitradurga',
  'Chikmagalūr',
  'Chhindwāra',
  'Chhatarpur',
  'Chāpra',
  'Chās',
  'Chānda',
  'Chandigarh',
  'Chanduasi',
  'Chandannagar',
  'Kolkata',
  'Burhānpur',
  'Bulandshahr',
  'Budaun',
  'Brahmapur',
  'Botād',
  'Borivli',
  'Mumbai',
  'Bokāro',
  'Bilimora',
  'Bilāspur',
  'Bīkaner',
  'Bijapur',
  'Bihār Sharīf',
  'Bīdar',
  'Bhusāval',
  'Bhuj',
  'Bhubaneshwar',
  'Bhopal',
  'Bhiwāni',
  'Bhiwandi',
  'Bhind',
  'Bhīmavaram',
  'Bhīlwāra',
  'Bhilai',
  'Bhayandar',
  'Bhavnagar',
  'Bhātpāra',
  'Bathinda',
  'Bharūch',
  'Bharatpur',
  'Bhāgalpur',
  'Bhadreswar',
  'Bhadrāvati',
  'Bettiah',
  'Bellary',
  'Belgaum',
  'Begusarai',
  'Beāwar',
  'Batāla',
  'Bastī',
  'Bārsi',
  'Barnāla',
  'Bareilly',
  'Barddhamān',
  'Bārāsat',
  'Bārāsat',
  'Baranagar',
  'Bārākpur',
  'Bānsbāria',
  'Bānkura',
  'Bangaon',
  'Bengaluru',
  'Bānda',
  'Bālurghāt',
  'Bāli',
  'Balasore',
  'Baidyabāti',
  'Bahraigh',
  'Baharampur',
  'Bahādurgarh',
  'Bagaha',
  'Badlapur',
  'Azamgarh',
  'Āvadi',
  'Aurangabad',
  'Āsansol',
  'Arrah',
  'Anantapur',
  'Anand',
  'Amroha',
  'Amritsar',
  'Amrāvati',
  'Ambur',
  'Ambattūr',
  'Ambāla',
  'Amarnāth',
  'Alwar',
  'Alappuzha',
  'Allahābād',
  'Alīgarh',
  'Alandur',
  'Akola',
  'Ajmer',
  'Aizawl',
  'Ahmadnagar',
  'Ahmedabad',
  'Agra',
  'Agartala',
  'Ādoni',
  'Ādilābād',
  'Achalpur',
  'Abohar',
  'Haldia',
  'Nangi',
  'Soyībug',
  'Navi Mumbai',
  'Panchkula',
  'Shivaji Nagar',
  'Greater Noida',
  'Mohali',
  'Airoli',
  'Noida',
  'Singrauli',
  'Jaigaon',
  'Lal Bahadur Nagar',
  'Malkajgiri',
  'Gajuwaka',
  'Quthbullapur',
  'Serilingampalle',
  'Ashoknagar Kalyangarh',
  'Ramagundam',
  'Thoothukudi',
  'Gadag-Betageri',
  'Kultali',
  'Deoli',
  'Rohini',
  'Umm Qaşr',
  'Sīnah',
  'Sāmarrā’',
  'Kirkuk',
  'Karbala',
  'Erbil',
  'Soran',
  'Dihok',
  'Baqubah',
  'Baghdad',
  'Az Zubayr',
  'As Sulaymānīyah',
  'As Samawah',
  'Ramadi',
  'Nasiriyah',
  'Najaf',
  'Al Mawşil al Jadīdah',
  'Mosul',
  'Al Kūt',
  'Kufa',
  'Al Ḩillah',
  'Al Fāw',
  'Al Fallūjah',
  'Basrah',
  'Al ‘Amārah',
  'Ad Dīwānīyah',
  'Abū Ghurayb',
  'Al Başrah al Qadīmah',
  'Āzādshahr',
  'Kahrīz',
  'Qarchak',
  'Zanjān',
  'Yazd',
  'Varāmīn',
  'Torbat-e Ḩeydarīyeh',
  'Tehran',
  'Tabriz',
  'Sirjan',
  'Shiraz',
  'Shahr-e Kord',
  'Semnan',
  'Sāveh',
  'Sari',
  'Saqqez',
  'Sanandaj',
  'Sabzevar',
  'Rasht',
  'Rafsanjān',
  'Qūchān',
  'Qom',
  'Qazvin',
  'Pārsābād',
  'Orūmīyeh',
  'Neyshābūr',
  'Naz̧arābād',
  'Mīāndoāb',
  'Masjed Soleymān',
  'Mashhad',
  'Marvdasht',
  'Marand',
  'Malāyer',
  'Mahābād',
  'Kūhdasht',
  'Khowy',
  'Khorramshahr',
  'Khorramabad',
  'Kermanshah',
  'Kerman',
  'Karaj',
  'Īlām',
  'Hamadān',
  'Gorgān',
  'Gonbad-e Kāvūs',
  'Shahrud',
  'Bushehr',
  'Būkān',
  'Borūjerd',
  'Bojnūrd',
  'Bīrjand',
  'Bāneh',
  'Bandar-e Anzalī',
  'Bandar Abbas',
  'Bābol',
  'Ardabīl',
  'Arāk',
  'Āmol',
  'Ahvaz',
  'Abadan',
  'Najafābād',
  'Khomeynī Shahr',
  'Isfahan',
  'Zābol',
  'Zahedan',
  'Iranshahr',
  'Pasragad Branch',
  'Reykjavík',
  'Reggio Calabria',
  'Palermo',
  'Messina',
  'Catania',
  'Cagliari',
  'Vicenza',
  'Verona',
  'Trieste',
  'Turin',
  'Taranto',
  'Salerno',
  'Rome',
  'Rimini',
  "Reggio nell'Emilia",
  'Prato',
  'Pescara',
  'Perugia',
  'Parma',
  'Padova',
  'Naples',
  'Monza',
  'Modena',
  'Milan',
  'Mestre',
  'Livorno',
  'Genoa',
  'Foggia',
  'Florence',
  'Brescia',
  'Bologna',
  'Bergamo',
  'Bari',
  'Acilia-Castel Fusano-Ostia Antica',
  'Spanish Town',
  'Portmore',
  'New Kingston',
  'Kingston',
  'Wādī as Sīr',
  'Irbid',
  'Zarqa',
  'Amman',
  '‘Ajlūn',
  'Russeifa',
  'Atsugi',
  'Akashi',
  'Zama',
  'Yono',
  'Yonago',
  'Yokosuka',
  'Yokohama',
  'Yokkaichi',
  'Honmachi',
  'Yao',
  'Yamaguchi',
  'Yaizu',
  'Utsunomiya',
  'Urayasu',
  'Uji',
  'Ueda',
  'Ube',
  'Tsu',
  'Toyota',
  'Toyonaka',
  'Toyokawa',
  'Toyohashi',
  'Toyama',
  'Tottori',
  'Tondabayashichō',
  'Tokyo',
  'Tokuyama',
  'Tokushima',
  'Tokorozawa',
  'Nishi-Tokyo-shi',
  'Takatsuki',
  'Takasaki',
  'Takarazuka',
  'Takaoka',
  'Takamatsu',
  'Tajimi',
  'Suzuka',
  'Suita',
  'Sōka',
  'Shizuoka',
  'Shimonoseki',
  'Minato',
  'Seto',
  'Sasebo',
  'Sandachō',
  'Sakata',
  'Sakai',
  'Saga',
  'Oyama',
  'Ōtsu',
  'Ōta',
  'Osaka',
  'Ōmuta',
  'Ōme',
  'Okazaki',
  'Okayama',
  'Ōita',
  'Ōgaki',
  'Odawara',
  'Numazu',
  'Noda',
  'Nobeoka',
  'Nishio',
  'Nishinomiya-hama',
  'Niihama',
  'Niigata',
  'Nara-shi',
  'Naha',
  'Nagoya',
  'Nagasaki',
  'Nagareyama',
  'Nagaoka',
  'Nagano',
  'Musashino',
  'Moriguchi',
  'Miyazaki',
  'Miyakonojō',
  'Mishima',
  'Mino',
  'Minamirinkan',
  'Matsumoto',
  'Matsue',
  'Matsudo',
  'Matsubara',
  'Maebashi',
  'Machida',
  'Kyoto',
  'Kusatsu',
  'Kurume',
  'Kure',
  'Kurashiki',
  'Kumamoto',
  'Kumagaya',
  'Koshigaya',
  'Kōnan',
  'Komatsu',
  'Komaki',
  'Kokubunji',
  'Kōfu',
  'Kochi',
  'Kobe',
  'Kitakyushu',
  'Kishiwada',
  'Kisarazu',
  'Kiryū',
  'Kawasaki',
  'Kawanishi',
  'Kawaguchi',
  'Kawagoe',
  'Kasukabe',
  'Kasugai',
  'Kashiwa',
  'Kashihara-shi',
  'Kariya',
  'Kanazawa',
  'Kamirenjaku',
  'Kamakura',
  'Kakogawachō-honmachi',
  'Kakamigahara',
  'Kagoshima',
  'Kadoma',
  'Izumisano',
  'Izumi',
  'Iwatsuki',
  'Iwakuni',
  'Itami',
  'Isesaki',
  'Isehara',
  'Inazawa',
  'Ikoma',
  'Iida',
  'Ichinomiya',
  'Ibaraki',
  'Hōfu',
  'Hiroshima',
  'Hiratsuka',
  'Hirakata',
  'Hino',
  'Himeji',
  'Hikone',
  'Handa',
  'Hamamatsu',
  'Hadano',
  'Hachiōji',
  'Gifu-shi',
  'Honchō',
  'Fukuyama',
  'Fukuoka',
  'Fukui-shi',
  'Fukayachō',
  'Fujisawa',
  'Fujinomiya',
  'Fujieda',
  'Fuji',
  'Daitōchō',
  'Chōfu',
  'Chikushino-shi',
  'Chigasaki',
  'Beppu',
  'Ashikaga',
  'Anjō',
  'Amagasaki',
  'Ageoshimo',
  'Okinawa',
  'Sayama',
  'Asaka',
  'Shimotoda',
  'Wakayama',
  'Matsuyama',
  'Yamagata',
  'Tsukuba',
  'Sendai',
  'Sakura',
  'Narita',
  'Morioka',
  'Mito',
  'Kōriyama',
  'Katsuta',
  'Iwaki',
  'Ishinomaki',
  'Ichihara',
  'Hitachi',
  'Fukushima',
  'Chiba',
  'Akita',
  'Abiko',
  'Tomakomai',
  'Sapporo',
  'Otaru',
  'Obihiro',
  'Kushiro',
  'Kitami',
  'Hirosaki',
  'Hakodate',
  'Hachinohe',
  'Ebetsu',
  'Asahikawa',
  'Aomori',
  'Neyagawa',
  'Hitachi-Naka',
  'Jōetsu',
  'Saitama',
  'Higashimurayama',
  'Kuwana',
  'Thika',
  'Nakuru',
  'Nairobi',
  'Mombasa',
  'Malindi',
  'Kisumu',
  'Eldoret',
  'Osh',
  'Bishkek',
  'Phnom Penh',
  'Takeo',
  'Siem Reap',
  'Sihanoukville',
  'Battambang',
  'Wŏnsan',
  'Sunch’ŏn',
  'Songnim',
  'Sariwŏn',
  'Pyongyang',
  'P’yŏngsŏng',
  'Namp’o',
  'Kaesŏng',
  'Hŭngnam',
  'Hamhŭng',
  'Haeju',
  'Sinŭiju',
  'Manp’o',
  'Kanggye',
  'Hyesan',
  'Chongjin',
  'Yangju',
  'Wŏnju',
  'Ulsan',
  'Uijeongbu-si',
  'Daejeon',
  'Daegu',
  'Suwon',
  'Suncheon',
  'Seoul',
  'Busan',
  'Bucheon-si',
  'Pohang',
  'Osan',
  'Mokpo',
  'Masan',
  'Gyeongsan-si',
  'Gyeongju',
  'Gwangju',
  'Guri-si',
  'Gunsan',
  'Gumi',
  'Goyang-si',
  'Kimhae',
  'Gimcheon',
  'Gangneung',
  'Iksan',
  'Incheon',
  'Icheon-si',
  'Hwaseong-si',
  'Chuncheon',
  'Jeonju',
  'Cheongju-si',
  'Cheonan',
  'Chinju',
  'Jeju City',
  'Changwon',
  'Anyang-si',
  'Ansan-si',
  'Andong',
  'Yeosu',
  'Tonghae',
  'Seongnam-si',
  'Hanam',
  'Hwado',
  'Kwangmyŏng',
  'Seogwipo',
  'Sejong',
  'Jeongeup',
  'Ḩawallī',
  'As Sālimīyah',
  'Al Aḩmadī',
  'Şabāḩ as Sālim',
  'Zhanaozen',
  'Oral',
  'Karagandy',
  'Atyrau',
  'Aktobe',
  'Aktau',
  'Zhezqazghan',
  'Taraz',
  'Temirtau',
  'Taldykorgan',
  'Shymkent',
  'Semey',
  'Rudnyy',
  'Kyzylorda',
  'Kostanay',
  'Petropavl',
  'Pavlodar',
  'Ust-Kamenogorsk',
  'Kokshetau',
  'Ekibastuz',
  'Nur-Sultan',
  'Almaty',
  'Vientiane',
  'Tripoli',
  'Tyre',
  'Sidon',
  'Ra’s Bayrūt',
  'Beirut',
  'Nabatîyé et Tahta',
  'Trincomalee',
  'Pita Kotte',
  'Negombo',
  'Dehiwala-Mount Lavinia',
  'Moratuwa',
  'Sri Jayewardenepura Kotte',
  'Kandy',
  'Kalmunai',
  'Jaffna',
  'Colombo',
  'Monrovia',
  'Maseru',
  'Vilnius',
  'Šiauliai',
  'Panevėžys',
  'Klaipėda',
  'Kaunas',
  'Riga',
  'Daugavpils',
  'Tobruk',
  'Benghazi',
  'Ajdabiya',
  'Zliten',
  'Tarhuna',
  'Tripoli',
  'Tagiura',
  'Sirte',
  'Şabrātah',
  'Sabhā',
  'Mişrātah',
  'Zawiya',
  'Az Zāwīyah',
  'Al Ajaylat',
  'Al Khums',
  'Al Jadīd',
  'Tétouan',
  'Temara',
  'Taza',
  'Tangier',
  'Settat',
  'Sale',
  'Safi',
  'Rabat',
  'Oujda-Angad',
  'Nador',
  'Mohammedia',
  'Meknès',
  'Marrakesh',
  'Larache',
  'Ksar El Kebir',
  'Khouribga',
  'Kenitra',
  'Fès al Bali',
  'Fès',
  'El Jadid',
  'Casablanca',
  'Beni Mellal',
  'Khemisset',
  'Al Hoceïma',
  'Agadir',
  'Salé Al Jadida',
  'Tiraspol',
  'Chisinau',
  'Bender',
  'Bălţi',
  'Podgorica',
  'Toamasina',
  'Toliara',
  'Mahajanga',
  'Fianarantsoa',
  'Antsirabe',
  'Antananarivo',
  'Skopje',
  'Sikasso',
  'Mopti',
  'Bamako',
  'Yenangyaung',
  'Taungoo',
  'Thaton',
  'Dawei',
  'Taunggyi',
  'Sittwe',
  'Yangon',
  'Pyay',
  'Bago',
  'Pakokku',
  'Myingyan',
  'Mawlamyine',
  'Monywa',
  'Myeik',
  'Meiktila',
  'Pyin Oo Lwin',
  'Mandalay',
  'Lashio',
  'Hinthada',
  'Pathein',
  'Nay Pyi Taw',
  'Kyain Seikgyi Township',
  'Ulan Bator',
  'Macau',
  'Nouakchott',
  'Vacoas',
  'Port Louis',
  'Beau Bassin-Rose Hill',
  'Male',
  'Mzuzu',
  'Lilongwe',
  'Blantyre',
  'Ciudad Valles',
  'Xochimilco',
  'Xico',
  'Álvaro Obregón',
  'Villahermosa',
  'Gustavo Adolfo Madero',
  'Veracruz',
  'Tuxtla',
  'Tulancingo',
  'Toluca',
  'Tlalpan',
  'Tlalnepantla',
  'Tláhuac',
  'Texcoco de Mora',
  'Cuautitlán Izcalli',
  'Tehuacán',
  'Tapachula',
  'Tampico',
  'Santa María Chimalhuacán',
  'San Pablo de las Salinas',
  'San Juan del Río',
  'Tuxtepec',
  'San Cristóbal de las Casas',
  'Reynosa',
  'Puebla',
  'Poza Rica de Hidalgo',
  'Playa del Carmen',
  'Pachuca de Soto',
  'Orizaba',
  'Oaxaca',
  'Nuevo Laredo',
  'Nicolás Romero',
  'Naucalpan de Juárez',
  'Miramar',
  'Minatitlán',
  'Mérida',
  'Heroica Matamoros',
  'Magdalena Contreras',
  'Jiutepec',
  'Xalapa de Enríquez',
  'Ixtapaluca',
  'Iztapalapa',
  'Iztacalco',
  'Iguala de la Independencia',
  'Ecatepec de Morelos',
  'Cuernavaca',
  'Cuautla',
  'Cuautitlán',
  'Delegación Cuajimalpa de Morelos',
  'Coyoacán',
  'Córdoba',
  'Coatzacoalcos',
  'Coacalco',
  'Ciudad Victoria',
  'Ciudad Nezahualcoyotl',
  'Ciudad Madero',
  'Mexico City',
  'Ciudad del Carmen',
  'Chilpancingo',
  'Chicoloapan',
  'Chetumal',
  'Chalco',
  'Cancún',
  'Campeche',
  'Azcapotzalco',
  'Ciudad López Mateos',
  'Acapulco de Juárez',
  'Tepexpan',
  'Benito Juarez',
  'Venustiano Carranza',
  'Miguel Hidalgo',
  'Cuauhtémoc',
  'Huixquilucan',
  'Ojo de Agua',
  'Buenavista',
  'Zapopan',
  'Zamora',
  'Zacatecas',
  'Ciudad de Villa de Álvarez',
  'Uruapan',
  'Torreón',
  'Tonalá',
  'Tlaquepaque',
  'Tijuana',
  'Tepic',
  'Soledad de Graciano Sánchez',
  'Santa Catarina',
  'San Nicolás de los Garza',
  'San Luis Río Colorado',
  'San Luis Potosí',
  'Saltillo',
  'Salamanca',
  'Santiago de Querétaro',
  'Puerto Vallarta',
  'Piedras Negras',
  'Navojoa',
  'Morelia',
  'Monterrey',
  'Monclova',
  'Mexicali',
  'Mazatlán',
  'Manzanillo',
  'Los Mochis',
  'León de los Aldama',
  'La Paz',
  'Ciudad Benito Juárez',
  'Irapuato',
  'Parral',
  'Nogales',
  'Hermosillo',
  'Heroica Guaymas',
  'Guadalupe',
  'Guadalupe',
  'Guadalajara',
  'Gómez Palacio',
  'Ciudad General Escobedo',
  'San Pedro Garza García',
  'Fresnillo',
  'Ensenada',
  'Victoria de Durango',
  'Culiacán',
  'Cuauhtémoc',
  'Colima',
  'Ciudad Obregón',
  'Juárez',
  'Ciudad Delicias',
  'Ciudad Acuña',
  'Chihuahua',
  'Celaya',
  'Ciudad Apodaca',
  'Aguascalientes',
  'Benito Juárez',
  'Colonia del Valle',
  'Colonia Lindavista',
  'San Pedro Garza Garcia',
  'Batu Pahat',
  'Kampung Pasir Gudang Baru',
  'Skudai',
  'Johor Bahru',
  'Kluang',
  'Muar',
  'Shah Alam',
  'Klang',
  'Kota Kinabalu',
  'Lahad Datu',
  'Sandakan',
  'Tawau',
  'Kulim',
  'Taiping',
  'Ipoh',
  'Kuala Terengganu',
  'Malacca',
  'Seremban',
  'Sepang',
  'Butterworth',
  'Bukit Mertajam',
  'Tasek Glugor',
  'George Town',
  'Rawang',
  'Petaling Jaya',
  'Kuala Lumpur',
  'Ampang',
  'Kuantan',
  'Sungai Petani',
  'Kuching',
  'Sibu',
  'Alor Setar',
  'Kota Bharu',
  'Bintulu',
  'Miri',
  'Kampung Sungai Ara',
  'Kampung Baru Subang',
  'Subang Jaya',
  'Xai-Xai',
  'Tete',
  'Ressano Garcia',
  'Quelimane',
  'Pemba',
  'Nampula',
  'Nacala',
  'Maxixe',
  'Matola',
  'Maputo',
  'Mandimba',
  'Lichinga',
  'Chimoio',
  'Beira',
  'Windhoek',
  'Zinder',
  'Niamey',
  'Maradi',
  'Agadez',
  'Zaria',
  'Warri',
  'Uyo',
  'Uromi',
  'Umuahia',
  'Ugep',
  'Suleja',
  'Sokoto',
  'Saki',
  'Shagamu',
  'Sapele',
  'Port Harcourt',
  'Pindiga',
  'Oyo',
  'Owo',
  'Owerri',
  'Osogbo',
  'Onitsha',
  'Ondo',
  'Okrika',
  'Okigwe',
  'Okene',
  'Offa',
  'Nsukka',
  'Nnewi',
  'Nkpor',
  'Nguru',
  'Mubi',
  'Modakeke',
  'Minna',
  'Makurdi',
  'Maiduguri',
  'Lekki',
  'Lagos',
  'Lafiagi',
  'Lafia',
  'Kisi',
  'Katsina',
  'Kano',
  'Kaduna',
  'Jos',
  'Jimeta',
  'Jalingo',
  'Iwo',
  'Ise-Ekiti',
  'Inisa',
  'Ilorin',
  'Ilobu',
  'Ilesa',
  'Ila Orangun',
  'Ikot Ekpene',
  'Ikirun',
  'Ikire',
  'Ikere-Ekiti',
  'Ikeja',
  'Ijero-Ekiti',
  'Ijebu-Ode',
  'Ijebu-Igbo',
  'Igboho',
  'Ibadan',
  'Hadejia',
  'Gusau',
  'Gombe',
  'Gbongan',
  'Gashua',
  'Funtua',
  'Esuk Oron',
  'Enugu',
  'Ejigbo',
  'Efon-Alaaye',
  'Ebute Ikorodu',
  'Calabar',
  'Buguma',
  'Birnin Kebbi',
  'Bida',
  'Benin City',
  'Bauchi',
  'Bama',
  'Azare',
  'Awka',
  'Atani',
  'Amaigbo',
  'Akure',
  'Ado-Ekiti',
  'Abuja',
  'Abeokuta',
  'Abakaliki',
  'Aba',
  'Chakwama',
  'Matagalpa',
  'Masaya',
  'Managua',
  'León',
  'Chinandega',
  'Zwolle',
  'Zoetermeer',
  'Zaanstad',
  'Utrecht',
  'Tilburg',
  "'s-Hertogenbosch",
  'The Hague',
  'Rotterdam',
  'Nijmegen',
  'Maastricht',
  'Leiden',
  'Hoofddorp',
  'Haarlem',
  'Groningen',
  'Enschede',
  'Eindhoven',
  'Dordrecht',
  'Breda',
  'Arnhem',
  'Apeldoorn',
  'Amsterdam',
  'Amersfoort',
  'Almere Stad',
  'Trondheim',
  'Stavanger',
  'Oslo',
  'Bergen',
  'Pokhara',
  'Pātan',
  'Kathmandu',
  'Dharān',
  'Birgañj',
  'Biratnagar',
  'Bharatpur',
  'Wellington',
  'North Shore',
  'Manukau City',
  'Lower Hutt',
  'Hamilton',
  'Dunedin',
  'Christchurch',
  'Auckland',
  'Tauranga',
  'Sohar',
  'Şalālah',
  'Muscat',
  '‘Ibrī',
  'Bawshar',
  'As Suwayq',
  'Seeb',
  'San Miguelito',
  'Panamá',
  'Juan Díaz',
  'Tumbes',
  'Trujillo',
  'Sullana',
  'Pucallpa',
  'Piura',
  'Iquitos',
  'Huánuco',
  'Chimbote',
  'Chiclayo',
  'Cajamarca',
  'Tacna',
  'Santiago de Surco',
  'Puno',
  'Lima',
  'Juliaca',
  'Ica',
  'Huancayo',
  'Cusco',
  'Chincha Alta',
  'Callao',
  'Ayacucho',
  'Arequipa',
  'Port Moresby',
  'Zamboanga',
  'Urdaneta',
  'Tuguegarao',
  'Toledo',
  'Taytay',
  'Tarlac City',
  'Tanza',
  'Talisay',
  'Magugpo Poblacion',
  'Taguig',
  'Tacloban',
  'Silang',
  'Santol',
  'Santiago',
  'Santa Rosa',
  'Santa Cruz',
  'San Pedro',
  'San Pablo',
  'San Mateo',
  'San Juan',
  'San Jose del Monte',
  'San Jose',
  'San Fernando',
  'Roxas City',
  'Quezon City',
  'Pulong Santa Cruz',
  'Puerto Princesa',
  'Pasay',
  'Panalanoy',
  'Pagadian',
  'Ormoc',
  'Olongapo',
  'Navotas',
  'Naga',
  'Muricay',
  'Rodriguez',
  'Meycauayan',
  'Mati',
  'Marawi City',
  'Mantampay',
  'Mansilingan',
  'Manila',
  'Mandaue City',
  'Mandaluyong City',
  'Malolos',
  'Makati City',
  'Mabalacat City',
  'Lucena',
  'Lipa City',
  'Libertad',
  'Legaspi',
  'Las Piñas',
  'Lapu-Lapu City',
  'Laoag',
  'Koronadal',
  'Kabankalan',
  'Jolo',
  'Imus',
  'Iloilo',
  'Iligan City',
  'Iligan',
  'Hagonoy',
  'Guyong',
  'General Santos',
  'Dumaguete',
  'Digos',
  'Davao',
  'Dasmariñas',
  'Dagupan',
  'Cotabato',
  'Cebu City',
  'Cavite City',
  'Caloocan City',
  'Calamba',
  'Cainta',
  'Cagayan de Oro',
  'Cadiz',
  'Cabuyao',
  'Cabanatuan City',
  'Butuan',
  'Bulaon',
  'Budta',
  'Binangonan',
  'Biñan',
  'Batangas',
  'Baliuag',
  'Baguio',
  'Bago City',
  'Bacoor',
  'Bacolod City',
  'Antipolo',
  'Angeles City',
  'Malingao',
  'Pasig City',
  'Khairpur Mir’s',
  'Wazirabad',
  'Vihari',
  'Tordher',
  'Tando Allahyar',
  'Tando Adam',
  'Sukkur',
  'Sialkot',
  'Shikarpur',
  'Shekhupura',
  'Shahkot',
  'Sargodha',
  'Sahiwal',
  'Saddiqabad',
  'Rawalpindi',
  'Rahim Yar Khan',
  'Quetta',
  'Peshawar',
  'Pakpattan',
  'Okara',
  'New Mirpur',
  'Nawabshah',
  'Muzaffargarh',
  'Muzaffarābād',
  'Muridke',
  'Multan',
  'Mirpur Khas',
  'Mingora',
  'Mardan',
  'Mandi Bahauddin',
  'Malir Cantonment',
  'Larkana',
  'Lahore',
  'Kotli',
  'Kot Addu',
  'Kohat',
  'Khuzdar',
  'Khushāb',
  'Khanpur',
  'Kasur',
  'Karachi',
  'Kamoke',
  'Kamalia',
  'Jhelum',
  'Jhang Sadr',
  'Jaranwala',
  'Jacobabad',
  'Islamabad',
  'Hyderabad',
  'Hafizabad',
  'Gujrat',
  'Gujranwala',
  'Gojra',
  'Faisalabad',
  'Dera Ismail Khan',
  'Dera Ghazi Khan',
  'Daska Kalan',
  'Dadu',
  'Chishtian',
  'Chiniot',
  'Chakwal',
  'Būrewāla',
  'Bhimbar',
  'Battagram',
  'Bahawalpur',
  'Bahawalnagar',
  'Ahmadpur East',
  'Abbottabad',
  'Bahawalnagar',
  'Wola',
  'Warsaw',
  'Tarnów',
  'Targówek',
  'Śródmieście',
  'Rzeszów',
  'Radom',
  'Olsztyn',
  'Mokotów',
  'Lublin',
  'Kielce',
  'Bielany',
  'Białystok',
  'Bemowo',
  'Zielona Góra',
  'Zabrze',
  'Wrocław',
  'Włocławek',
  'Wałbrzych',
  'Tychy',
  'Toruń',
  'Szczecin',
  'Sosnowiec',
  'Rybnik',
  'Ruda Śląska',
  'Poznań',
  'Płock',
  'Opole',
  'Łódź',
  'Legnica',
  'Kraków',
  'Koszalin',
  'Katowice',
  'Kalisz',
  'Gorzów Wielkopolski',
  'Gliwice',
  'Gdynia',
  'Gdańsk',
  'Elbląg',
  'Dąbrowa Górnicza',
  'Częstochowa',
  'Chorzów',
  'Bytom',
  'Bydgoszcz',
  'Bielsko-Biala',
  'Ursynów',
  'Praga Południe',
  'Bayamón',
  'Carolina',
  'Ponce',
  'San Juan',
  'Rafaḩ',
  'Khān Yūnis',
  'Jabālyā',
  'Gaza',
  'Nablus',
  'Hebron',
  'East Jerusalem',
  'Setúbal',
  'Queluz',
  'Lisbon',
  'Funchal',
  'Amadora',
  'Porto',
  'Coimbra',
  'Braga',
  'San Lorenzo',
  'Lambaré',
  'Fernando de la Mora',
  'Ciudad del Este',
  'Capiatá',
  'Asunción',
  'Ar Rayyān',
  'Doha',
  'Saint-Denis',
  'Târgu-Mureş',
  'Timişoara',
  'Suceava',
  'Sibiu',
  'Satu Mare',
  'Râmnicu Vâlcea',
  'Ploieşti',
  'Piteşti',
  'Piatra Neamţ',
  'Oradea',
  'Iaşi',
  'Galaţi',
  'Drobeta-Turnu Severin',
  'Craiova',
  'Constanţa',
  'Cluj-Napoca',
  'Buzău',
  'Bucharest',
  'Braşov',
  'Brăila',
  'Botoşani',
  'Baia Mare',
  'Bacău',
  'Arad',
  'Sector 1',
  'Sector 2',
  'Sector 3',
  'Sector 4',
  'Sector 5',
  'Sector 6',
  'Zemun',
  'Niš',
  'Kragujevac',
  'Čačak',
  'Belgrade',
  'Subotica',
  'Novi Sad',
  'Zyuzino',
  'Zyablikovo',
  'Zlatoust',
  'Zhulebino',
  'Zheleznodorozhnyy',
  'Zelenograd',
  'Yoshkar-Ola',
  'Yelets',
  'Yasenevo',
  'Yaroslavl',
  'Vykhino-Zhulebino',
  'Voronezh',
  'Volzhskiy',
  'Vologda',
  'Volgograd',
  'Volgodonsk',
  'Vladimir',
  'Vladikavkaz',
  'Veshnyaki',
  'Velikiye Luki',
  'Ulyanovsk',
  'Ukhta',
  'Ufa',
  'Tver',
  'Tula',
  'Troparëvo',
  'Tol’yatti',
  'Tyoply Stan',
  'Tekstil’shchiki',
  'Tambov',
  'Taganrog',
  'Taganskiy',
  'Syzran’',
  'Syktyvkar',
  'Strogino',
  'Sterlitamak',
  'Stavropol’',
  'Staryy Oskol',
  'Solntsevo',
  'Solikamsk',
  'Sochi',
  'Smolensk',
  'Shchukino',
  'Shchelkovo',
  'Shakhty',
  'Severodvinsk',
  'Severnyy',
  'Serpukhov',
  'Sergiyev Posad',
  'Saratov',
  'Saransk',
  'Saint Petersburg',
  'Samara',
  'Salavat',
  'Rybinsk',
  'Ryazan’',
  'Rostov-na-Donu',
  'Ramenki',
  'Pyatigorsk',
  'Pushkino',
  'Pskov',
  'Podolsk',
  'Ryazanskiy',
  'Petrozavodsk',
  'Pervoural’sk',
  'Perm',
  'Novo-Peredelkino',
  'Penza',
  'Orsk',
  'Orenburg',
  'Orël',
  'Orekhovo-Zuyevo',
  'Orekhovo-Borisovo Severnoye',
  'Oktyabr’skiy',
  'Odintsovo',
  'Ochakovo-Matveyevskoye',
  'Obninsk',
  'Novyye Kuz’minki',
  'Novyye Cherëmushki',
  'Novotroitsk',
  'Novorossiysk',
  'Novomoskovsk',
  'Novokuybyshevsk',
  'Novocherkassk',
  'Novocheboksarsk',
  'Velikiy Novgorod',
  'Noginsk',
  'Nizhny Tagil',
  'Nizhniy Novgorod',
  'Nizhnekamsk',
  'Nevinnomyssk',
  'Neftekamsk',
  'Nazran’',
  'Nal’chik',
  'Naberezhnyye Chelny',
  'Mytishchi',
  'Murom',
  'Murmansk',
  'Moscow',
  'Maykop',
  'Mar’ino',
  'Makhachkala',
  'Magnitogorsk',
  'Lyublino',
  'Lyubertsy',
  'Lipetsk',
  'Tsaritsyno',
  'Kuz’minki',
  'Kursk',
  'Krasnodar',
  'Presnenskiy',
  'Kovrov',
  'Kostroma',
  'Kolpino',
  'Kolomna',
  'Kislovodsk',
  'Kirov',
  'Khoroshëvo-Mnevniki',
  'Khimki',
  'Khasavyurt',
  'Kazan',
  'Kamyshin',
  'Kaluga',
  'Korolev',
  'Kaliningrad',
  'Izmaylovo',
  'Izhevsk',
  'Ivanovskoye',
  'Ivanovo',
  'Groznyy',
  'Gol’yanovo',
  'Glazov',
  'Engel’s',
  'Elista',
  'Elektrostal’',
  'Dzerzhinsk',
  'Dimitrovgrad',
  'Derbent',
  'Cherkessk',
  'Cherepovets',
  'Cherëmushki',
  'Cheboksary',
  'Bryansk',
  'Brateyevo',
  'Bogorodskoye',
  'Biryulëvo',
  'Bibirevo',
  'Berezniki',
  'Belgorod',
  'Bataysk',
  'Balashikha',
  'Balakovo',
  'Astrakhan',
  'Arzamas',
  'Armavir',
  'Arkhangel’sk',
  'Al’met’yevsk',
  'Yekaterinburg',
  'Tyumen',
  'Tomsk',
  'Tobol’sk',
  'Surgut',
  'Rubtsovsk',
  'Prokop’yevsk',
  'Omsk',
  'Noyabrsk',
  'Novosibirsk',
  'Novokuznetsk',
  'Norilsk',
  'Nizhnevartovsk',
  'Nefteyugansk',
  'Miass',
  'Mezhdurechensk',
  'Leninsk-Kuznetsky',
  'Kyzyl',
  'Kurgan',
  'Krasnoyarsk',
  'Kiselëvsk',
  'Kemerovo',
  'Kansk',
  'Kamensk-Ural’skiy',
  'Chelyabinsk',
  'Biysk',
  'Barnaul',
  'Achinsk',
  'Abakan',
  'Seversk',
  'Yakutsk',
  'Vladivostok',
  'Ust’-Ilimsk',
  'Ussuriysk',
  'Ulan-Ude',
  'Nakhodka',
  'Komsomolsk-on-Amur',
  'Khabarovsk',
  'Irkutsk',
  'Chita',
  'Blagoveshchensk',
  'Artëm',
  'Angarsk',
  'Bratsk',
  'Khabarovsk Vtoroy',
  'Yuzhno-Sakhalinsk',
  'Petropavlovsk-Kamchatsky',
  'Chertanovo Yuzhnoye',
  'Orekhovo-Borisovo',
  'Petrogradka',
  "Vasyl'evsky Ostrov",
  'Kalininskiy',
  'Krasnogvargeisky',
  'Admiralteisky',
  'Akademicheskoe',
  'Centralniy',
  'Kigali',
  'Yanbu',
  'Tabuk',
  'Sulţānah',
  'Sakakah',
  'Najrān',
  'Mecca',
  'Khamis Mushait',
  'Jizan',
  'Jeddah',
  "Ha'il",
  'Hafar Al-Batin',
  'Buraydah',
  'Ta’if',
  'Riyadh',
  'Arar',
  'Qurayyat',
  'Al Mubarraz',
  'Medina',
  'Khobar',
  'Al Kharj',
  'Al Jubayl',
  'Al Hufūf',
  'Dammam',
  'Abha',
  'Wad Medani',
  'Omdurman',
  'Singa',
  'Sinnar',
  'Rabak',
  'Nyala',
  'Kosti',
  'Kassala',
  'Port Sudan',
  'Atbara',
  'An Nuhūd',
  'El Obeid',
  'Al Qadarif',
  'Al Manāqil',
  'Khartoum',
  'Geneina',
  'El Fasher',
  'El Daein',
  'Ed Damer',
  'Ad-Damazin',
  'Gereida',
  'Västerås',
  'Uppsala',
  'Stockholm',
  'Sollentuna',
  'Södermalm',
  'Örebro',
  'Malmö',
  'Linköping',
  'Helsingborg',
  'Göteborg',
  'Singapore',
  'Woodlands',
  'Ljubljana',
  'Košice',
  'Bratislava',
  'Kenema',
  'Freetown',
  'Bo',
  'Ziguinchor',
  'Touba',
  'Tiébo',
  'Thiès Nones',
  'Thiès',
  'Saint-Louis',
  'Pikine',
  'Kaolack',
  'Dakar',
  'Mogadishu',
  'Marka',
  'Kismayo',
  'Jamaame',
  'Hargeysa',
  'Berbera',
  'Baidoa',
  'Paramaribo',
  'Winejok',
  'Wau',
  'Malakal',
  'Juba',
  'Soyapango',
  'Santa Ana',
  'San Salvador',
  'San Miguel',
  'Santa Tecla',
  'Mejicanos',
  'Apopa',
  'Idlib',
  'Homs',
  'Ḩamāh',
  'Aleppo',
  'Douma',
  'Damascus',
  'Deir ez-Zor',
  'Ar Raqqah',
  'Latakia',
  'Al Bāb',
  'Manzini',
  'Sarh',
  "N'Djamena",
  'Moundou',
  'Sokodé',
  'Lomé',
  'Kara',
  'Surat Thani',
  'Nakhon Si Thammarat',
  'Lampang',
  'Chiang Mai',
  'Udon Thani',
  'Ubon Ratchathani',
  'Si Racha',
  'Samut Prakan',
  'Rayong',
  'Phra Pradaeng',
  'Phitsanulok',
  'Pak Kret',
  'Mueang Nonthaburi',
  'Nakhon Ratchasima',
  'Nakhon Pathom',
  'Bangkok',
  'Khon Kaen',
  'Khlong Luang',
  'Hat Yai',
  'Chon Buri',
  'Dushanbe',
  'Khujand',
  'Dili',
  'Ashgabat',
  'Daşoguz',
  'Mary',
  'Türkmenabat',
  'Tunis',
  'Sousse',
  'Sfax',
  'Gabès',
  'Bizerte',
  'Kairouan',
  'Viranşehir',
  'Van',
  'Uşak',
  'Şanlıurfa',
  'Turgutlu',
  'Tarsus',
  'Siverek',
  'Sivas',
  'Siirt',
  'Osmaniye',
  'Nazilli',
  'Mersin',
  'Manisa',
  'Malatya',
  'Kütahya',
  'Konya',
  'Kızıltepe',
  'Kırıkkale',
  'Kayseri',
  'Karaman',
  'Kahramanmaraş',
  'İzmir',
  'Isparta',
  'İskenderun',
  'Gaziantep',
  'Eskişehir',
  'Erzurum',
  'Erzincan',
  'Elazığ',
  'Diyarbakır',
  'Denizli',
  'Batman',
  'Balıkesir',
  'Aydın',
  'Antalya',
  'Antakya',
  'Ankara',
  'Alanya',
  'Aksaray',
  'Afyonkarahisar',
  'Adıyaman',
  'Adana',
  'Batikent',
  'Zonguldak',
  'Zeytinburnu',
  'Üsküdar',
  'Umraniye',
  'Turhal',
  'Trabzon',
  'Tokat',
  'Tekirdağ',
  'Şişli',
  'Samsun',
  'Ordu',
  'Mustafakemalpaşa',
  'Maltepe',
  'İzmit',
  'Istanbul',
  'İnegol',
  'Gebze',
  'Esenyurt',
  'Esenler',
  'Edirne',
  'Derince',
  'Çorum',
  'Çorlu',
  'Bursa',
  'Bandırma',
  'Bağcılar',
  'Arnavutköy',
  'Adapazarı',
  'Ataşehir',
  'Başakşehir',
  'Beylikdüzü',
  'Büyükçekmece',
  'Çankaya',
  'Bahçelievler',
  'Sultangazi',
  'Sultanbeyli',
  'Sancaktepe',
  'Karabağlar',
  'Muratpaşa',
  'Merkezefendi',
  'Douliu',
  'Yuanlin',
  'Taipei',
  'Tainan',
  'Taichung',
  'Banqiao',
  'Nantou',
  'Kaohsiung',
  'Hualien City',
  'Hsinchu',
  'Keelung',
  'Taoyuan City',
  'Taitung City',
  'Zanzibar',
  'Tanga',
  'Tabora',
  'Shinyanga',
  'Mwanza',
  'Musoma',
  'Moshi',
  'Morogoro',
  'Mbeya',
  'Kigoma',
  'Katumba',
  'Iringa',
  'Dodoma',
  'Dar es Salaam',
  'Arusha',
  'Songea',
  'Zhytomyr',
  'Zaporizhia',
  'Yevpatoriya',
  'Yenakiyeve',
  'Vinnytsia',
  'Uzhgorod',
  'Ternopil',
  'Syevyerodonets’k',
  'Sumy',
  'Sloviansk',
  'Simferopol',
  'Sevastopol',
  'Rivne',
  'Poltava',
  'Pavlohrad',
  'Oleksandriya',
  'Odessa',
  'Nikopol',
  'Mykolayiv',
  'Melitopol',
  'Mariupol',
  'Makiyivka',
  'Lviv',
  'Lutsk',
  'Luhansk',
  'Lysychans’k',
  'Kyiv',
  'Kryvyi Rih',
  'Kremenchuk',
  'Kramators’k',
  'Kropyvnytskyi',
  'Khmelnytskyi',
  'Kherson',
  'Kharkiv',
  'Kerch',
  'Kamianets-Podilskyi',
  'Ivano-Frankivsk',
  'Horlivka',
  'Donetsk',
  'Dnipro',
  'Kamianske',
  'Chernivtsi',
  'Chernihiv',
  'Cherkasy',
  'Bila Tserkva',
  'Berdyansk',
  'Alchevs’k',
  'Lira',
  'Kampala',
  'Gulu',
  'Birmingham',
  'Huntsville',
  'Mobile',
  'Montgomery',
  'Little Rock',
  'Washington, D.C.',
  'Brandon',
  'Cape Coral',
  'Clearwater',
  'Coral Springs',
  'Davie',
  'Fort Lauderdale',
  'Gainesville',
  'Hialeah',
  'Hollywood',
  'Jacksonville',
  'Lakeland',
  'Miami',
  'Miami Gardens',
  'Miramar',
  'Orlando',
  'Palm Bay',
  'Pembroke Pines',
  'Pompano Beach',
  'Port Saint Lucie',
  'St. Petersburg',
  'Tallahassee',
  'Tampa',
  'West Palm Beach',
  'Athens',
  'Atlanta',
  'Columbus',
  'Sandy Springs',
  'Savannah',
  'Springfield',
  'Evansville',
  'Indianapolis',
  'Kansas City',
  'Olathe',
  'Overland Park',
  'Topeka',
  'Wichita',
  'Ironville',
  'Lexington',
  'Lexington-Fayette',
  'Louisville',
  'Meads',
  'Baton Rouge',
  'Lafayette',
  'Metairie',
  'Metairie Terrace',
  'New Orleans',
  'Shreveport',
  'Baltimore',
  'Columbia',
  'East Independence',
  'Independence',
  'Kansas City',
  'St. Louis',
  'Springfield',
  'Jackson',
  'Cary',
  'Charlotte',
  'Durham',
  'Fayetteville',
  'Greensboro',
  'High Point',
  'Raleigh',
  'West Raleigh',
  'Wilmington',
  'Winston-Salem',
  'Cincinnati',
  'Columbus',
  'Dayton',
  'Broken Arrow',
  'Norman',
  'Oklahoma City',
  'Tulsa',
  'Philadelphia',
  'Charleston',
  'Columbia',
  'North Charleston',
  'Chattanooga',
  'Clarksville',
  'East Chattanooga',
  'Knoxville',
  'Memphis',
  'Murfreesboro',
  'Nashville',
  'New South Memphis',
  'Abilene',
  'Arlington',
  'Austin',
  'Beaumont',
  'Brownsville',
  'Carrollton',
  'College Station',
  'Corpus Christi',
  'Dallas',
  'Denton',
  'Fort Worth',
  'Frisco',
  'Garland',
  'Grand Prairie',
  'Houston',
  'Irving',
  'Killeen',
  'Laredo',
  'Lewisville',
  'McAllen',
  'McKinney',
  'Mesquite',
  'Pasadena',
  'Pearland',
  'Plano',
  'Richardson',
  'Round Rock',
  'San Antonio',
  'Tyler',
  'Waco',
  'Wichita Falls',
  'Alexandria',
  'Arlington',
  'Chesapeake',
  'East Hampton',
  'Hampton',
  'Newport News',
  'Norfolk',
  'Richmond',
  'Virginia Beach',
  'Hartford',
  'New Haven',
  'North Stamford',
  'Stamford',
  'Waterbury',
  'Cedar Rapids',
  'Davenport',
  'Des Moines',
  'Aurora',
  'Chicago',
  'Elgin',
  'Joliet',
  'Naperville',
  'North Peoria',
  'Peoria',
  'Rockford',
  'Fort Wayne',
  'South Bend',
  'Boston',
  'Cambridge',
  'Lowell',
  'South Boston',
  'Springfield',
  'Worcester',
  'Ann Arbor',
  'Detroit',
  'Grand Rapids',
  'Lansing',
  'Sterling Heights',
  'Warren',
  'Minneapolis',
  'Rochester',
  'Saint Paul',
  'Fargo',
  'Lincoln',
  'Omaha',
  'Manchester',
  'Edison',
  'Elizabeth',
  'Jersey City',
  'Newark',
  'Paterson',
  'Amherst',
  'Astoria',
  'Borough Park',
  'The Bronx',
  'Brooklyn',
  'Buffalo',
  'Bushwick',
  'Corona',
  'East Flatbush',
  'East New York',
  'Elmhurst',
  'Gravesend',
  'Harlem',
  'Jamaica',
  'Manhattan',
  'New York City',
  'Queens',
  'Rochester',
  'Sheepshead Bay',
  'Staten Island',
  'Syracuse',
  'Washington Heights',
  'Yonkers',
  'Akron',
  'Cleveland',
  'Toledo',
  'Allentown',
  'Pittsburgh',
  'Providence',
  'Sioux Falls',
  'Green Bay',
  'Madison',
  'Milwaukee',
  'Bridgeport',
  'Chandler',
  'Deer Valley',
  'Gilbert',
  'Glendale',
  'Maryvale',
  'Mesa',
  'Peoria',
  'Phoenix',
  'Scottsdale',
  'Surprise',
  'Tempe',
  'Tempe Junction',
  'Tucson',
  'Anaheim',
  'Antioch',
  'Bakersfield',
  'Berkeley',
  'Burbank',
  'Carlsbad',
  'Chinatown',
  'Chula Vista',
  'Clovis',
  'Concord',
  'Corona',
  'Costa Mesa',
  'Daly City',
  'Downey',
  'East Los Angeles',
  'El Cajon',
  'El Monte',
  'Elk Grove',
  'Escondido',
  'Fairfield',
  'Fontana',
  'Fremont',
  'Fresno',
  'Fullerton',
  'Garden Grove',
  'Glendale',
  'Hayward',
  'Hollywood',
  'Huntington Beach',
  'Inglewood',
  'Irvine',
  'Koreatown',
  'Lancaster',
  'Long Beach',
  'Los Angeles',
  'Modesto',
  'Moreno Valley',
  'Murrieta',
  'Norwalk',
  'Oakland',
  'Oceanside',
  'Ontario',
  'Orange',
  'Oxnard',
  'Palmdale',
  'Pasadena',
  'Pomona',
  'Rancho Cucamonga',
  'Rialto',
  'Richmond',
  'Riverside',
  'Roseville',
  'Sacramento',
  'Salinas',
  'San Bernardino',
  'San Diego',
  'San Francisco',
  'San Jose',
  'San Mateo',
  'Santa Ana',
  'Santa Clara',
  'Santa Clarita',
  'Santa Maria',
  'Santa Rosa',
  'Simi Valley',
  'Stockton',
  'Sunnyvale',
  'Temecula',
  'Thousand Oaks',
  'Torrance',
  'Universal City',
  'Valencia',
  'Vallejo',
  'Van Nuys',
  'Victorville',
  'Visalia',
  'Vista',
  'West Covina',
  'Arvada',
  'Aurora',
  'Centennial',
  'Colorado Springs',
  'Denver',
  'Lakewood',
  'Pueblo',
  'Thornton',
  'Westminster',
  'Albuquerque',
  'Las Cruces',
  'Enterprise',
  'Henderson',
  'Las Vegas',
  'North Las Vegas',
  'Paradise',
  'Reno',
  'Spring Valley',
  'Sunrise Manor',
  'Amarillo',
  'El Paso',
  'Lubbock',
  'Midland',
  'Odessa',
  'San Angelo',
  'Alhambra',
  'Boulder',
  'Fort Collins',
  'Greeley',
  'Boise',
  'Billings',
  'Eugene',
  'Gresham',
  'Hillsboro',
  'Portland',
  'Salem',
  'Provo',
  'Salt Lake City',
  'West Jordan',
  'West Valley City',
  'Bellevue',
  'Everett',
  'Kent',
  'Renton',
  'Seattle',
  'Spokane',
  'Tacoma',
  'Vancouver',
  'Honolulu',
  'Anchorage',
  'East Harlem',
  'Sunset Park',
  'Montevideo',
  'Nukus',
  'Tirmiz',
  'Samarkand',
  'Qarshi',
  'Bukhara',
  'Urganch',
  'Tashkent',
  'Qo‘qon',
  'Olmaliq',
  'Navoiy',
  'Namangan',
  'Marg‘ilon',
  'Jizzax',
  'Fergana',
  'Chirchiq',
  'Angren',
  'Andijon',
  'Anaco',
  'Alto Barinas',
  'Valencia',
  'Turmero',
  'Santa Teresa del Tuy',
  'San Cristóbal',
  'Punto Fijo',
  'Puerto La Cruz',
  'Puerto Cabello',
  'Petare',
  'Palo Negro',
  'Ocumare del Tuy',
  'Mucumpiz',
  'Mérida',
  'Mariara',
  'Maracay',
  'Maracaibo',
  'Los Teques',
  'Guatire',
  'Guarenas',
  'Guanare',
  'Guacara',
  'El Tigre',
  'El Limón',
  'Ejido',
  'Cumaná',
  'Cúa',
  'Coro',
  'Ciudad Guayana',
  'Ciudad Bolívar',
  'Charallave',
  'Catia La Mar',
  'Carúpano',
  'Caracas',
  'Calabozo',
  'Cagua',
  'Cabimas',
  'Baruta',
  'Barquisimeto',
  'Barinas',
  'Barcelona',
  'Acarigua',
  'Maturín',
  'Yên Vinh',
  'Vũng Tàu',
  'Vĩnh Long',
  'Vinh',
  'Ho Chi Minh City',
  'Thanh Hóa',
  'Thái Nguyên',
  'Sóc Trăng',
  'Sa Dec',
  'Rạch Giá',
  'Qui Nhon',
  'Pleiku',
  'Phan Thiết',
  'Nha Trang',
  'Nam Định',
  'Mỹ Tho',
  'Long Xuyên',
  'La Gi',
  'Huế',
  'Hạ Long',
  'Hòa Bình',
  'Hanoi',
  'Haiphong',
  'Đưc Trọng',
  'Da Nang',
  'Ðà Lạt',
  'Cần Thơ',
  'Cần Giuộc',
  'Cam Ranh',
  'Cẩm Phả Mines',
  'Cà Mau',
  'Buôn Ma Thuột',
  'Biên Hòa',
  'Bảo Lộc',
  'Bạc Liêu',
  'Thị Xã Phú Mỹ',
  'Prizren',
  'Pristina',
  'Mitrovicë',
  'Ta‘izz',
  'Sanaa',
  'Ibb',
  'Dhamār',
  'Mukalla',
  'Al Ḩudaydah',
  'Aden',
  'Roodepoort',
  'Witbank',
  'Westonaria',
  'Welkom',
  'Vryheid',
  'Virginia',
  'Vereeniging',
  'Vanderbijlpark',
  'Uitenhage',
  'Tembisa',
  'Springs',
  'Soweto',
  'Rustenburg',
  'Richards Bay',
  'Randfontein',
  'Randburg',
  'Queenstown',
  'Pretoria',
  'Mokopane',
  'Potchefstroom',
  'Port Elizabeth',
  'Polokwane',
  'Pietermaritzburg',
  'Phalaborwa',
  'Orkney',
  'Nigel',
  'Newcastle',
  'Nelspruit',
  'Mpumalanga',
  'Middelburg',
  'Krugersdorp',
  'Kroonstad',
  'Klerksdorp',
  'Kimberley',
  'Johannesburg',
  'eMbalenhle',
  'East London',
  'Durban',
  'Carletonville',
  'Brits',
  'Brakpan',
  'Botshabelo',
  'Boksburg',
  'Bloemfontein',
  'Bhisho',
  'Bethal',
  'Benoni',
  'Alberton',
  'Midrand',
  'Centurion',
  'Worcester',
  'Paarl',
  'Cape Town',
  'Diepsloot',
  'Ndola',
  'Mufulira',
  'Lusaka',
  'Luanshya',
  'Livingstone',
  'Kitwe',
  'Kabwe',
  'Chingola',
  'Mutare',
  'Harare',
  'Gweru',
  'Bulawayo',
  'Epworth',
  'Chitungwiza'
]
